# Pruebas Estadísticas

```{r pruebas-setup, include=FALSE}
library(DescTools)
library(summarytools)
library(patchwork)
library(janitor)
library(tidymodels)
library(tidyverse)

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  error = FALSE,
  # fig.path = "figs/",
  fig.retina = 3,
  fig.width = 8,
  fig.asp = 0.618,
  fig.align = "center",
  out.width = "70%"
)

theme_set(theme_bw(base_size = 12))

```

## Introducción

## Pruebas estadísticas

## Tamaño del Efecto

## Datos cuantitativos

### $\chi^2$ para 1 varianza

### $F$ para 2 varianzas

### $Z$ de 1 muestra

### $t$ de 1 muestra

### $t$ de 2 muestras independientes

### $t$ de 2 muestras dependientes

### $t$ de correlación

### Análisis de Varianza (ANOVA)

## Datos cualitativos

### Bondad de ajuste

### Homogeneidad

### Independencia / asociación

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
