<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 17 Estadística Direccional | Geología Numérica: Ciencia de Datos para Geociencias</title>
  <meta name="description" content="Este documento compila el funcionamiento básico del software estadístico y de programación R, así como rutinas y/o comandos específicos para resolver problemas de análisis de datos en geociencias." />
  <meta name="generator" content="bookdown 0.11 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 17 Estadística Direccional | Geología Numérica: Ciencia de Datos para Geociencias" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Este documento compila el funcionamiento básico del software estadístico y de programación R, así como rutinas y/o comandos específicos para resolver problemas de análisis de datos en geociencias." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 17 Estadística Direccional | Geología Numérica: Ciencia de Datos para Geociencias" />
  
  <meta name="twitter:description" content="Este documento compila el funcionamiento básico del software estadístico y de programación R, así como rutinas y/o comandos específicos para resolver problemas de análisis de datos en geociencias." />
  

<meta name="author" content="Maximiliano Garnier Villarreal" />


<meta name="date" content="2020-07-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="estadística-no-paramétrica.html">
<link rel="next" href="secuencias-de-datos.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/dygraphs-1.1.1/shapes.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.6/dygraphs.js"></script>
<script src="libs/plotly-binding-4.9.2/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.11/datatables.js"></script>
<link href="libs/dt-core-1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.19/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.19/js/jquery.dataTables.min.js"></script>
<link href="libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet" />
<script src="libs/nouislider-7.0.10/jquery.nouislider.min.js"></script>
<link href="libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet" />
<script src="libs/selectize-0.12.0/selectize.min.js"></script>
<script src="libs/proj4js-2.3.15/proj4.js"></script>
<link href="libs/highcharts-7.0.1/css/motion.css" rel="stylesheet" />
<link href="libs/highcharts-7.0.1/css/htmlwdgtgrid.css" rel="stylesheet" />
<script src="libs/highcharts-7.0.1/highcharts.js"></script>
<script src="libs/highcharts-7.0.1/highcharts-3d.js"></script>
<script src="libs/highcharts-7.0.1/highcharts-more.js"></script>
<script src="libs/highcharts-7.0.1/modules/stock.js"></script>
<script src="libs/highcharts-7.0.1/modules/map.js"></script>
<script src="libs/highcharts-7.0.1/modules/annotations.js"></script>
<script src="libs/highcharts-7.0.1/modules/boost.js"></script>
<script src="libs/highcharts-7.0.1/modules/data.js"></script>
<script src="libs/highcharts-7.0.1/modules/drag-panes.js"></script>
<script src="libs/highcharts-7.0.1/modules/drilldown.js"></script>
<script src="libs/highcharts-7.0.1/modules/item-series.js"></script>
<script src="libs/highcharts-7.0.1/modules/offline-exporting.js"></script>
<script src="libs/highcharts-7.0.1/modules/overlapping-datalabels.js"></script>
<script src="libs/highcharts-7.0.1/modules/exporting.js"></script>
<script src="libs/highcharts-7.0.1/modules/export-data.js"></script>
<script src="libs/highcharts-7.0.1/modules/funnel.js"></script>
<script src="libs/highcharts-7.0.1/modules/heatmap.js"></script>
<script src="libs/highcharts-7.0.1/modules/treemap.js"></script>
<script src="libs/highcharts-7.0.1/modules/sankey.js"></script>
<script src="libs/highcharts-7.0.1/modules/solid-gauge.js"></script>
<script src="libs/highcharts-7.0.1/modules/streamgraph.js"></script>
<script src="libs/highcharts-7.0.1/modules/sunburst.js"></script>
<script src="libs/highcharts-7.0.1/modules/vector.js"></script>
<script src="libs/highcharts-7.0.1/modules/wordcloud.js"></script>
<script src="libs/highcharts-7.0.1/modules/xrange.js"></script>
<script src="libs/highcharts-7.0.1/modules/tilemap.js"></script>
<script src="libs/highcharts-7.0.1/modules/venn.js"></script>
<script src="libs/highcharts-7.0.1/modules/gantt.js"></script>
<script src="libs/highcharts-7.0.1/modules/timeline.js"></script>
<script src="libs/highcharts-7.0.1/modules/parallel-coordinates.js"></script>
<script src="libs/highcharts-7.0.1/plugins/grouped-categories.js"></script>
<script src="libs/highcharts-7.0.1/plugins/motion.js"></script>
<script src="libs/highcharts-7.0.1/plugins/multicolor_series.js"></script>
<script src="libs/highcharts-7.0.1/custom/reset.js"></script>
<script src="libs/highcharts-7.0.1/custom/symbols-extra.js"></script>
<script src="libs/highcharts-7.0.1/custom/text-symbols.js"></script>
<script src="libs/highchart-binding-0.7.0/highchart.js"></script>
<script src="libs/highcharts-regression.js-7.0.1/highcharts-regression.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.2/leaflet.js"></script>
<script src="libs/leaflet-providers-1.1.17/leaflet-providers.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.2/leaflet-providers-plugin.js"></script>
<link href="libs/HomeButton-0.0.1/home-button.css" rel="stylesheet" />
<script src="libs/HomeButton-0.0.1/home-button.js"></script>
<script src="libs/HomeButton-0.0.1/easy-button-src.min.js"></script>
<script src="libs/clipboard-0.0.1/setClipboardText.js"></script>
<link href="libs/PopupTable-0.0.1/popup.css" rel="stylesheet" />
<script src="libs/pacifico-1/data_stars_pacificocdf13b.txt"></script>
<script src="libs/joda-0.0.1/joda.js"></script>
<script src="libs/joda-0.0.1/addImageQuery-bindings.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Geologia Numerica</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefacio</a></li>
<li class="part"><span><b>R</b></span></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a><ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#instalación-de-r-y-rstudio"><i class="fa fa-check"></i><b>1.1</b> Instalación de R y RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#paquetes"><i class="fa fa-check"></i><b>1.2</b> Paquetes</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#ayuda-en-r"><i class="fa fa-check"></i><b>1.3</b> Ayuda en R</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#rmarkdown"><i class="fa fa-check"></i><b>1.4</b> RMarkdown</a><ul>
<li class="chapter" data-level="1.4.1" data-path="intro.html"><a href="intro.html#tipos-de-resultados"><i class="fa fa-check"></i><b>1.4.1</b> Tipos de resultados</a></li>
<li class="chapter" data-level="1.4.2" data-path="intro.html"><a href="intro.html#formulas"><i class="fa fa-check"></i><b>1.4.2</b> Formulas</a></li>
<li class="chapter" data-level="1.4.3" data-path="intro.html"><a href="intro.html#importando-datos"><i class="fa fa-check"></i><b>1.4.3</b> Importando datos</a></li>
<li class="chapter" data-level="1.4.4" data-path="intro.html"><a href="intro.html#cálculos-en-linea"><i class="fa fa-check"></i><b>1.4.4</b> Cálculos en linea</a></li>
<li class="chapter" data-level="1.4.5" data-path="intro.html"><a href="intro.html#importando-figuras"><i class="fa fa-check"></i><b>1.4.5</b> Importando figuras</a></li>
<li class="chapter" data-level="1.4.6" data-path="intro.html"><a href="intro.html#salvando-y-compartiendo"><i class="fa fa-check"></i><b>1.4.6</b> Salvando y compartiendo</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#recursos"><i class="fa fa-check"></i><b>1.5</b> Recursos</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basico.html"><a href="basico.html"><i class="fa fa-check"></i><b>2</b> Funcionamiento básico de R</a><ul>
<li class="chapter" data-level="2.1" data-path="basico.html"><a href="basico.html#introducción"><i class="fa fa-check"></i><b>2.1</b> Introducción</a></li>
<li class="chapter" data-level="2.2" data-path="basico.html"><a href="basico.html#operaciones-básicas"><i class="fa fa-check"></i><b>2.2</b> Operaciones básicas</a></li>
<li class="chapter" data-level="2.3" data-path="basico.html"><a href="basico.html#crear-objetos"><i class="fa fa-check"></i><b>2.3</b> Crear objetos</a></li>
<li class="chapter" data-level="2.4" data-path="basico.html"><a href="basico.html#vectores"><i class="fa fa-check"></i><b>2.4</b> Vectores</a><ul>
<li class="chapter" data-level="2.4.1" data-path="basico.html"><a href="basico.html#numéricos"><i class="fa fa-check"></i><b>2.4.1</b> Numéricos</a></li>
<li class="chapter" data-level="2.4.2" data-path="basico.html"><a href="basico.html#texto-string-character"><i class="fa fa-check"></i><b>2.4.2</b> Texto (string, character)</a></li>
<li class="chapter" data-level="2.4.3" data-path="basico.html"><a href="basico.html#categóricos-factores"><i class="fa fa-check"></i><b>2.4.3</b> Categóricos (factores)</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="basico.html"><a href="basico.html#matrices"><i class="fa fa-check"></i><b>2.5</b> Matrices</a></li>
<li class="chapter" data-level="2.6" data-path="basico.html"><a href="basico.html#dataframes-listas-y-tibbles"><i class="fa fa-check"></i><b>2.6</b> DataFrames, listas y tibbles</a></li>
<li class="chapter" data-level="2.7" data-path="basico.html"><a href="basico.html#verificando-objetos"><i class="fa fa-check"></i><b>2.7</b> Verificando objetos</a></li>
<li class="chapter" data-level="2.8" data-path="basico.html"><a href="basico.html#guardando-el-espacio-de-trabajo"><i class="fa fa-check"></i><b>2.8</b> Guardando el espacio de trabajo</a></li>
<li class="chapter" data-level="2.9" data-path="basico.html"><a href="basico.html#importandocargando-datos"><i class="fa fa-check"></i><b>2.9</b> Importando/cargando datos</a></li>
<li class="chapter" data-level="2.10" data-path="basico.html"><a href="basico.html#exportando-datos"><i class="fa fa-check"></i><b>2.10</b> Exportando datos</a></li>
<li class="chapter" data-level="2.11" data-path="basico.html"><a href="basico.html#inspeccionando-los-datos"><i class="fa fa-check"></i><b>2.11</b> Inspeccionando los datos</a></li>
<li class="chapter" data-level="2.12" data-path="basico.html"><a href="basico.html#descripciones-generales-globales"><i class="fa fa-check"></i><b>2.12</b> Descripciones generales (globales)</a></li>
<li class="chapter" data-level="2.13" data-path="basico.html"><a href="basico.html#recursos-1"><i class="fa fa-check"></i><b>2.13</b> Recursos</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="avanzado.html"><a href="avanzado.html"><i class="fa fa-check"></i><b>3</b> Funcionamiento avanzado de R</a><ul>
<li class="chapter" data-level="3.1" data-path="avanzado.html"><a href="avanzado.html#introducción-1"><i class="fa fa-check"></i><b>3.1</b> Introducción</a></li>
<li class="chapter" data-level="3.2" data-path="avanzado.html"><a href="avanzado.html#operadores-lógicos"><i class="fa fa-check"></i><b>3.2</b> Operadores lógicos</a></li>
<li class="chapter" data-level="3.3" data-path="avanzado.html"><a href="avanzado.html#operador-de-secuencia-pipe-operator"><i class="fa fa-check"></i><b>3.3</b> Operador de secuencia (Pipe operator)</a></li>
<li class="chapter" data-level="3.4" data-path="avanzado.html"><a href="avanzado.html#resumen-de-variables"><i class="fa fa-check"></i><b>3.4</b> Resumen de variables</a></li>
<li class="chapter" data-level="3.5" data-path="avanzado.html"><a href="avanzado.html#selección-y-renombre-de-variables"><i class="fa fa-check"></i><b>3.5</b> Selección y renombre de variables</a><ul>
<li class="chapter" data-level="3.5.1" data-path="avanzado.html"><a href="avanzado.html#select-helpers"><i class="fa fa-check"></i><b>3.5.1</b> <code>select</code> helpers</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="avanzado.html"><a href="avanzado.html#filtrado-de-observaciones"><i class="fa fa-check"></i><b>3.6</b> Filtrado de observaciones</a></li>
<li class="chapter" data-level="3.7" data-path="avanzado.html"><a href="avanzado.html#orden-de-acuerdo-a-variables"><i class="fa fa-check"></i><b>3.7</b> Orden de acuerdo a variables</a></li>
<li class="chapter" data-level="3.8" data-path="avanzado.html"><a href="avanzado.html#creación-de-variables"><i class="fa fa-check"></i><b>3.8</b> Creación de variables</a></li>
<li class="chapter" data-level="3.9" data-path="avanzado.html"><a href="avanzado.html#conteo-de-variables-cualitativas"><i class="fa fa-check"></i><b>3.9</b> Conteo de variables cualitativas</a></li>
<li class="chapter" data-level="3.10" data-path="avanzado.html"><a href="avanzado.html#tabla-interactiva"><i class="fa fa-check"></i><b>3.10</b> Tabla interactiva</a></li>
<li class="chapter" data-level="3.11" data-path="avanzado.html"><a href="avanzado.html#datos-relacionales"><i class="fa fa-check"></i><b>3.11</b> Datos relacionales</a><ul>
<li class="chapter" data-level="3.11.1" data-path="avanzado.html"><a href="avanzado.html#uniones-de-transformación"><i class="fa fa-check"></i><b>3.11.1</b> Uniones de transformación</a></li>
<li class="chapter" data-level="3.11.2" data-path="avanzado.html"><a href="avanzado.html#uniones-de-filtro"><i class="fa fa-check"></i><b>3.11.2</b> Uniones de filtro</a></li>
</ul></li>
<li class="chapter" data-level="3.12" data-path="avanzado.html"><a href="avanzado.html#datos-ordenados-tidy-data"><i class="fa fa-check"></i><b>3.12</b> Datos ordenados (Tidy data)</a><ul>
<li class="chapter" data-level="3.12.1" data-path="avanzado.html"><a href="avanzado.html#formatos-largo-y-ancho"><i class="fa fa-check"></i><b>3.12.1</b> Formatos largo y ancho</a></li>
<li class="chapter" data-level="3.12.2" data-path="avanzado.html"><a href="avanzado.html#separar-y-unir"><i class="fa fa-check"></i><b>3.12.2</b> Separar y unir</a></li>
</ul></li>
<li class="chapter" data-level="3.13" data-path="avanzado.html"><a href="avanzado.html#nest"><i class="fa fa-check"></i><b>3.13</b> Datos anidados (Nesting)</a></li>
<li class="chapter" data-level="3.14" data-path="avanzado.html"><a href="avanzado.html#recursos-2"><i class="fa fa-check"></i><b>3.14</b> Recursos</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="gráficos-1.html"><a href="gráficos-1.html"><i class="fa fa-check"></i><b>4</b> Gráficos</a><ul>
<li class="chapter" data-level="4.1" data-path="gráficos-1.html"><a href="gráficos-1.html#introducción-2"><i class="fa fa-check"></i><b>4.1</b> Introducción</a></li>
<li class="chapter" data-level="4.2" data-path="gráficos-1.html"><a href="gráficos-1.html#estáticos"><i class="fa fa-check"></i><b>4.2</b> Estáticos</a><ul>
<li class="chapter" data-level="4.2.1" data-path="gráficos-1.html"><a href="gráficos-1.html#histograma"><i class="fa fa-check"></i><b>4.2.1</b> Histograma</a></li>
<li class="chapter" data-level="4.2.2" data-path="gráficos-1.html"><a href="gráficos-1.html#barras"><i class="fa fa-check"></i><b>4.2.2</b> Barras</a></li>
<li class="chapter" data-level="4.2.3" data-path="gráficos-1.html"><a href="gráficos-1.html#boxplot"><i class="fa fa-check"></i><b>4.2.3</b> Boxplot</a></li>
<li class="chapter" data-level="4.2.4" data-path="gráficos-1.html"><a href="gráficos-1.html#dispersión"><i class="fa fa-check"></i><b>4.2.4</b> Dispersión</a></li>
<li class="chapter" data-level="4.2.5" data-path="gráficos-1.html"><a href="gráficos-1.html#líneas"><i class="fa fa-check"></i><b>4.2.5</b> líneas</a></li>
<li class="chapter" data-level="4.2.6" data-path="gráficos-1.html"><a href="gráficos-1.html#gráficos-estadísticos"><i class="fa fa-check"></i><b>4.2.6</b> Gráficos estadísticos</a></li>
<li class="chapter" data-level="4.2.7" data-path="gráficos-1.html"><a href="gráficos-1.html#transformación-de-ejes"><i class="fa fa-check"></i><b>4.2.7</b> Transformación de ejes</a></li>
<li class="chapter" data-level="4.2.8" data-path="gráficos-1.html"><a href="gráficos-1.html#limites-de-ejes-zoom"><i class="fa fa-check"></i><b>4.2.8</b> Limites de ejes (Zoom)</a></li>
<li class="chapter" data-level="4.2.9" data-path="gráficos-1.html"><a href="gráficos-1.html#salvando-gráficos"><i class="fa fa-check"></i><b>4.2.9</b> Salvando gráficos</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="gráficos-1.html"><a href="gráficos-1.html#interactivos"><i class="fa fa-check"></i><b>4.3</b> Interactivos</a><ul>
<li class="chapter" data-level="4.3.1" data-path="gráficos-1.html"><a href="gráficos-1.html#histograma-1"><i class="fa fa-check"></i><b>4.3.1</b> Histograma</a></li>
<li class="chapter" data-level="4.3.2" data-path="gráficos-1.html"><a href="gráficos-1.html#barras-1"><i class="fa fa-check"></i><b>4.3.2</b> Barras</a></li>
<li class="chapter" data-level="4.3.3" data-path="gráficos-1.html"><a href="gráficos-1.html#boxplot-1"><i class="fa fa-check"></i><b>4.3.3</b> Boxplot</a></li>
<li class="chapter" data-level="4.3.4" data-path="gráficos-1.html"><a href="gráficos-1.html#dispersión-1"><i class="fa fa-check"></i><b>4.3.4</b> Dispersión</a></li>
<li class="chapter" data-level="4.3.5" data-path="gráficos-1.html"><a href="gráficos-1.html#líneas-1"><i class="fa fa-check"></i><b>4.3.5</b> líneas</a></li>
<li class="chapter" data-level="4.3.6" data-path="gráficos-1.html"><a href="gráficos-1.html#transformación-de-ejes-1"><i class="fa fa-check"></i><b>4.3.6</b> Transformación de ejes</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="gráficos-1.html"><a href="gráficos-1.html#recursos-3"><i class="fa fa-check"></i><b>4.4</b> Recursos</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="iteración.html"><a href="iteración.html"><i class="fa fa-check"></i><b>5</b> Iteración</a><ul>
<li class="chapter" data-level="5.1" data-path="iteración.html"><a href="iteración.html#introducción-3"><i class="fa fa-check"></i><b>5.1</b> Introducción</a></li>
<li class="chapter" data-level="5.2" data-path="iteración.html"><a href="iteración.html#iterando-sobre-un-objeto"><i class="fa fa-check"></i><b>5.2</b> Iterando sobre un objeto</a></li>
<li class="chapter" data-level="5.3" data-path="iteración.html"><a href="iteración.html#iterando-sobre-dos-objetos"><i class="fa fa-check"></i><b>5.3</b> Iterando sobre dos objetos</a></li>
<li class="chapter" data-level="5.4" data-path="iteración.html"><a href="iteración.html#leyendo-archivos-y-combinándolos"><i class="fa fa-check"></i><b>5.4</b> Leyendo archivos y combinándolos</a></li>
<li class="chapter" data-level="5.5" data-path="iteración.html"><a href="iteración.html#datos-anidados-caso-1"><i class="fa fa-check"></i><b>5.5</b> Datos anidados, caso 1</a><ul>
<li class="chapter" data-level="5.5.1" data-path="iteración.html"><a href="iteración.html#efectos-secundarios"><i class="fa fa-check"></i><b>5.5.1</b> Efectos secundarios</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="iteración.html"><a href="iteración.html#datos-anidados-caso-2"><i class="fa fa-check"></i><b>5.6</b> Datos anidados, caso 2</a></li>
<li class="chapter" data-level="5.7" data-path="iteración.html"><a href="iteración.html#recursos-4"><i class="fa fa-check"></i><b>5.7</b> Recursos</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="datos-espaciales.html"><a href="datos-espaciales.html"><i class="fa fa-check"></i><b>6</b> Datos espaciales</a><ul>
<li class="chapter" data-level="6.1" data-path="datos-espaciales.html"><a href="datos-espaciales.html#introducción-4"><i class="fa fa-check"></i><b>6.1</b> Introducción</a></li>
<li class="chapter" data-level="6.2" data-path="datos-espaciales.html"><a href="datos-espaciales.html#paquetes-para-datos-espaciales"><i class="fa fa-check"></i><b>6.2</b> Paquetes para datos espaciales</a></li>
<li class="chapter" data-level="6.3" data-path="datos-espaciales.html"><a href="datos-espaciales.html#sistemas-de-referencias-de-coordenadas-crs"><i class="fa fa-check"></i><b>6.3</b> Sistemas de Referencias de Coordenadas (CRS)</a></li>
<li class="chapter" data-level="6.4" data-path="datos-espaciales.html"><a href="datos-espaciales.html#importar-datos"><i class="fa fa-check"></i><b>6.4</b> Importar datos</a><ul>
<li class="chapter" data-level="6.4.1" data-path="datos-espaciales.html"><a href="datos-espaciales.html#desde-archivos-de-texto"><i class="fa fa-check"></i><b>6.4.1</b> Desde archivos de texto</a></li>
<li class="chapter" data-level="6.4.2" data-path="datos-espaciales.html"><a href="datos-espaciales.html#desde-archivos-espaciales"><i class="fa fa-check"></i><b>6.4.2</b> Desde archivos espaciales</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="datos-espaciales.html"><a href="datos-espaciales.html#exportar-datos"><i class="fa fa-check"></i><b>6.5</b> Exportar datos</a><ul>
<li class="chapter" data-level="6.5.1" data-path="datos-espaciales.html"><a href="datos-espaciales.html#vectoriales"><i class="fa fa-check"></i><b>6.5.1</b> Vectoriales</a></li>
<li class="chapter" data-level="6.5.2" data-path="datos-espaciales.html"><a href="datos-espaciales.html#raster-1"><i class="fa fa-check"></i><b>6.5.2</b> Raster</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="datos-espaciales.html"><a href="datos-espaciales.html#mapas"><i class="fa fa-check"></i><b>6.6</b> Mapas</a><ul>
<li class="chapter" data-level="6.6.1" data-path="datos-espaciales.html"><a href="datos-espaciales.html#estáticos-1"><i class="fa fa-check"></i><b>6.6.1</b> Estáticos</a></li>
<li class="chapter" data-level="6.6.2" data-path="datos-espaciales.html"><a href="datos-espaciales.html#dinámicos"><i class="fa fa-check"></i><b>6.6.2</b> Dinámicos</a></li>
<li class="chapter" data-level="6.6.3" data-path="datos-espaciales.html"><a href="datos-espaciales.html#modelos-de-sombras"><i class="fa fa-check"></i><b>6.6.3</b> Modelos de sombras</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="datos-espaciales.html"><a href="datos-espaciales.html#recursos-5"><i class="fa fa-check"></i><b>6.7</b> Recursos</a></li>
</ul></li>
<li class="part"><span><b>Análisis de datos</b></span></li>
<li class="chapter" data-level="7" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html"><i class="fa fa-check"></i><b>7</b> Álgebra lineal</a><ul>
<li class="chapter" data-level="7.1" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html#introducción-5"><i class="fa fa-check"></i><b>7.1</b> Introducción</a></li>
<li class="chapter" data-level="7.2" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html#tensores"><i class="fa fa-check"></i><b>7.2</b> Tensores</a><ul>
<li class="chapter" data-level="7.2.1" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html#vectores-1"><i class="fa fa-check"></i><b>7.2.1</b> Vectores</a></li>
<li class="chapter" data-level="7.2.2" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html#matrices-1"><i class="fa fa-check"></i><b>7.2.2</b> Matrices</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html#eigenvectors-y-eigenvalues"><i class="fa fa-check"></i><b>7.3</b> Eigenvectors y Eigenvalues</a><ul>
<li class="chapter" data-level="7.3.1" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html#definición"><i class="fa fa-check"></i><b>7.3.1</b> Definición</a></li>
<li class="chapter" data-level="7.3.2" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html#cálculo"><i class="fa fa-check"></i><b>7.3.2</b> Cálculo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html"><i class="fa fa-check"></i><b>8</b> Introducción a estadística</a><ul>
<li class="chapter" data-level="8.1" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#introducción-6"><i class="fa fa-check"></i><b>8.1</b> Introducción</a></li>
<li class="chapter" data-level="8.2" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#tipos"><i class="fa fa-check"></i><b>8.2</b> Tipos</a></li>
<li class="chapter" data-level="8.3" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#modelos"><i class="fa fa-check"></i><b>8.3</b> Modelos</a></li>
<li class="chapter" data-level="8.4" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#nomenclatura"><i class="fa fa-check"></i><b>8.4</b> Nomenclatura</a></li>
<li class="chapter" data-level="8.5" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#variables"><i class="fa fa-check"></i><b>8.5</b> Variables</a><ul>
<li class="chapter" data-level="8.5.1" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#cualitativa"><i class="fa fa-check"></i><b>8.5.1</b> Cualitativa</a></li>
<li class="chapter" data-level="8.5.2" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#cuantitativa"><i class="fa fa-check"></i><b>8.5.2</b> Cuantitativa</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#métodos-de-análisis"><i class="fa fa-check"></i><b>8.6</b> Métodos de análisis</a></li>
<li class="chapter" data-level="8.7" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#muestreo"><i class="fa fa-check"></i><b>8.7</b> Muestreo</a><ul>
<li class="chapter" data-level="8.7.1" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#tipos-1"><i class="fa fa-check"></i><b>8.7.1</b> Tipos</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#incertidumbre"><i class="fa fa-check"></i><b>8.8</b> Incertidumbre</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html"><i class="fa fa-check"></i><b>9</b> Estadística Descriptiva Univariable</a><ul>
<li class="chapter" data-level="9.1" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#introducción-7"><i class="fa fa-check"></i><b>9.1</b> Introducción</a></li>
<li class="chapter" data-level="9.2" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#tablas-de-frecuencias"><i class="fa fa-check"></i><b>9.2</b> Tablas de frecuencias</a></li>
<li class="chapter" data-level="9.3" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#gráficas"><i class="fa fa-check"></i><b>9.3</b> Gráficas</a></li>
<li class="chapter" data-level="9.4" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#resúmenes-numéricos"><i class="fa fa-check"></i><b>9.4</b> Resúmenes numéricos</a><ul>
<li class="chapter" data-level="9.4.1" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#medidas-de-tendencia-central"><i class="fa fa-check"></i><b>9.4.1</b> Medidas de tendencia central</a></li>
<li class="chapter" data-level="9.4.2" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#medidas-de-dispersión"><i class="fa fa-check"></i><b>9.4.2</b> Medidas de dispersión</a></li>
<li class="chapter" data-level="9.4.3" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#medidas-de-posición"><i class="fa fa-check"></i><b>9.4.3</b> Medidas de posición</a></li>
<li class="chapter" data-level="9.4.4" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#medidas-de-forma"><i class="fa fa-check"></i><b>9.4.4</b> Medidas de forma</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#resumen-general"><i class="fa fa-check"></i><b>9.5</b> Resumen general</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html"><i class="fa fa-check"></i><b>10</b> Estadística Descriptiva Bivariable</a><ul>
<li class="chapter" data-level="10.1" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#introducción-8"><i class="fa fa-check"></i><b>10.1</b> Introducción</a></li>
<li class="chapter" data-level="10.2" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#covarianza"><i class="fa fa-check"></i><b>10.2</b> Covarianza</a></li>
<li class="chapter" data-level="10.3" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#bivar-cor"><i class="fa fa-check"></i><b>10.3</b> Correlación</a></li>
<li class="chapter" data-level="10.4" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#bivar-reg"><i class="fa fa-check"></i><b>10.4</b> Regresión</a><ul>
<li class="chapter" data-level="10.4.1" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#nomenclatura-1"><i class="fa fa-check"></i><b>10.4.1</b> Nomenclatura</a></li>
<li class="chapter" data-level="10.4.2" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#supuestos"><i class="fa fa-check"></i><b>10.4.2</b> Supuestos</a></li>
<li class="chapter" data-level="10.4.3" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#tipos-2"><i class="fa fa-check"></i><b>10.4.3</b> Tipos</a></li>
<li class="chapter" data-level="10.4.4" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#medidas-de-ajuste-y-error"><i class="fa fa-check"></i><b>10.4.4</b> Medidas de ajuste y error</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="probabilidad.html"><a href="probabilidad.html"><i class="fa fa-check"></i><b>11</b> Probabilidad</a><ul>
<li class="chapter" data-level="11.1" data-path="probabilidad.html"><a href="probabilidad.html#introducción-9"><i class="fa fa-check"></i><b>11.1</b> Introducción</a></li>
<li class="chapter" data-level="11.2" data-path="probabilidad.html"><a href="probabilidad.html#axiomas-y-nomenclatura"><i class="fa fa-check"></i><b>11.2</b> Axiomas y Nomenclatura</a></li>
<li class="chapter" data-level="11.3" data-path="probabilidad.html"><a href="probabilidad.html#reglas-de-probabilidad"><i class="fa fa-check"></i><b>11.3</b> Reglas de probabilidad</a><ul>
<li class="chapter" data-level="11.3.1" data-path="probabilidad.html"><a href="probabilidad.html#regla-de-la-suma"><i class="fa fa-check"></i><b>11.3.1</b> Regla de la suma</a></li>
<li class="chapter" data-level="11.3.2" data-path="probabilidad.html"><a href="probabilidad.html#regla-de-la-multiplicación"><i class="fa fa-check"></i><b>11.3.2</b> Regla de la multiplicación</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="probabilidad.html"><a href="probabilidad.html#variables-aleatorias"><i class="fa fa-check"></i><b>11.4</b> Variables aleatorias</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="distribuciones-de-probabilidad.html"><a href="distribuciones-de-probabilidad.html"><i class="fa fa-check"></i><b>12</b> Distribuciones de Probabilidad</a><ul>
<li class="chapter" data-level="12.1" data-path="distribuciones-de-probabilidad.html"><a href="distribuciones-de-probabilidad.html#introducción-10"><i class="fa fa-check"></i><b>12.1</b> Introducción</a></li>
<li class="chapter" data-level="12.2" data-path="distribuciones-de-probabilidad.html"><a href="distribuciones-de-probabilidad.html#distribución-binomial"><i class="fa fa-check"></i><b>12.2</b> Distribución Binomial</a></li>
<li class="chapter" data-level="12.3" data-path="distribuciones-de-probabilidad.html"><a href="distribuciones-de-probabilidad.html#distribución-de-poisson"><i class="fa fa-check"></i><b>12.3</b> Distribución de Poisson</a></li>
<li class="chapter" data-level="12.4" data-path="distribuciones-de-probabilidad.html"><a href="distribuciones-de-probabilidad.html#distribución-normal-o-gaussiana"><i class="fa fa-check"></i><b>12.4</b> Distribución Normal o Gaussiana</a><ul>
<li class="chapter" data-level="12.4.1" data-path="distribuciones-de-probabilidad.html"><a href="distribuciones-de-probabilidad.html#distribución-normal-estándar-z"><i class="fa fa-check"></i><b>12.4.1</b> Distribución Normal Estándar (Z)</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="distribuciones-de-probabilidad.html"><a href="distribuciones-de-probabilidad.html#distribuciones-de-probabilidad-en-r"><i class="fa fa-check"></i><b>12.5</b> Distribuciones de probabilidad en <strong>R</strong></a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="introducción-a-estadística-inferencial.html"><a href="introducción-a-estadística-inferencial.html"><i class="fa fa-check"></i><b>13</b> Introducción a Estadística Inferencial</a><ul>
<li class="chapter" data-level="13.1" data-path="introducción-a-estadística-inferencial.html"><a href="introducción-a-estadística-inferencial.html#introducción-11"><i class="fa fa-check"></i><b>13.1</b> Introducción</a></li>
<li class="chapter" data-level="13.2" data-path="introducción-a-estadística-inferencial.html"><a href="introducción-a-estadística-inferencial.html#distribuciones-muestrales"><i class="fa fa-check"></i><b>13.2</b> Distribuciones muestrales</a><ul>
<li class="chapter" data-level="13.2.1" data-path="introducción-a-estadística-inferencial.html"><a href="introducción-a-estadística-inferencial.html#infer-x"><i class="fa fa-check"></i><b>13.2.1</b> Media <span class="math inline">\((\bar{x})\)</span></a></li>
<li class="chapter" data-level="13.2.2" data-path="introducción-a-estadística-inferencial.html"><a href="introducción-a-estadística-inferencial.html#infer-x2"><i class="fa fa-check"></i><b>13.2.2</b> Diferencia de medias <span class="math inline">\((\bar{x}_1-\bar{x}_2)\)</span></a></li>
<li class="chapter" data-level="13.2.3" data-path="introducción-a-estadística-inferencial.html"><a href="introducción-a-estadística-inferencial.html#infer-chi"><i class="fa fa-check"></i><b>13.2.3</b> Varianza <span class="math inline">\((s^2)\)</span></a></li>
<li class="chapter" data-level="13.2.4" data-path="introducción-a-estadística-inferencial.html"><a href="introducción-a-estadística-inferencial.html#infer-f"><i class="fa fa-check"></i><b>13.2.4</b> Dos varianzas <span class="math inline">\(\left( \frac{s_1^2}{s_2^2} \right)\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html"><i class="fa fa-check"></i><b>14</b> Estimación e Hipótesis</a><ul>
<li class="chapter" data-level="14.1" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#introducción-12"><i class="fa fa-check"></i><b>14.1</b> Introducción</a></li>
<li class="chapter" data-level="14.2" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#estim"><i class="fa fa-check"></i><b>14.2</b> Estimación</a><ul>
<li class="chapter" data-level="14.2.1" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#media-1"><i class="fa fa-check"></i><b>14.2.1</b> Media</a></li>
<li class="chapter" data-level="14.2.2" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#estim-diff-medias"><i class="fa fa-check"></i><b>14.2.2</b> Diferencia de medias</a></li>
<li class="chapter" data-level="14.2.3" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#estim-ic-chi"><i class="fa fa-check"></i><b>14.2.3</b> Varianza</a></li>
<li class="chapter" data-level="14.2.4" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#estim-ic-f"><i class="fa fa-check"></i><b>14.2.4</b> Dos varianzas</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#hip"><i class="fa fa-check"></i><b>14.3</b> Hipótesis</a><ul>
<li class="chapter" data-level="14.3.1" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#nula-h_0-y-alterna-h_1"><i class="fa fa-check"></i><b>14.3.1</b> Nula (<span class="math inline">\(H_0\)</span>) y Alterna (<span class="math inline">\(H_1\)</span>)</a></li>
<li class="chapter" data-level="14.3.2" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#resultados-y-errores"><i class="fa fa-check"></i><b>14.3.2</b> Resultados y Errores</a></li>
<li class="chapter" data-level="14.3.3" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#estadístico-de-prueba-y-crítico"><i class="fa fa-check"></i><b>14.3.3</b> Estadístico de prueba y crítico</a></li>
<li class="chapter" data-level="14.3.4" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#contrastes-y-valor-p"><i class="fa fa-check"></i><b>14.3.4</b> Contrastes y valor-<em>p</em></a></li>
<li class="chapter" data-level="14.3.5" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#decisión"><i class="fa fa-check"></i><b>14.3.5</b> Decisión</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html"><i class="fa fa-check"></i><b>15</b> Pruebas Estadísticas</a><ul>
<li class="chapter" data-level="15.1" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#introducción-13"><i class="fa fa-check"></i><b>15.1</b> Introducción</a></li>
<li class="chapter" data-level="15.2" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#pruebas-param"><i class="fa fa-check"></i><b>15.2</b> Pruebas paramétricas</a><ul>
<li class="chapter" data-level="15.2.1" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#supuestos-pasos"><i class="fa fa-check"></i><b>15.2.1</b> Supuestos y Pasos</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#ES-p"><i class="fa fa-check"></i><b>15.3</b> Tamaño del Efecto</a><ul>
<li class="chapter" data-level="15.3.1" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#familias-de-tamaño-del-efecto"><i class="fa fa-check"></i><b>15.3.1</b> Familias de tamaño del efecto</a></li>
<li class="chapter" data-level="15.3.2" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#ecuaciones-para-tamaños-de-efecto"><i class="fa fa-check"></i><b>15.3.2</b> Ecuaciones para tamaños de efecto</a></li>
<li class="chapter" data-level="15.3.3" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#clasificación-de-tamaños-de-efecto"><i class="fa fa-check"></i><b>15.3.3</b> Clasificación de tamaños de efecto</a></li>
<li class="chapter" data-level="15.3.4" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#importancia-del-tamaño-del-efecto"><i class="fa fa-check"></i><b>15.3.4</b> Importancia del tamaño del efecto</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-z1"><i class="fa fa-check"></i><b>15.4</b> <span class="math inline">\(z\)</span> de 1 muestra</a></li>
<li class="chapter" data-level="15.5" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-t1"><i class="fa fa-check"></i><b>15.5</b> <span class="math inline">\(t\)</span> de 1 muestra</a></li>
<li class="chapter" data-level="15.6" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-t2-ind"><i class="fa fa-check"></i><b>15.6</b> <span class="math inline">\(t\)</span> de 2 muestras independientes</a></li>
<li class="chapter" data-level="15.7" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-t2-dep"><i class="fa fa-check"></i><b>15.7</b> <span class="math inline">\(t\)</span> de 2 muestras dependientes</a></li>
<li class="chapter" data-level="15.8" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-aov"><i class="fa fa-check"></i><b>15.8</b> ANOVA de 1-factor entre-sujetos</a><ul>
<li class="chapter" data-level="15.8.1" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#relación-entre-la-prueba-t-de-2-muestras-independientes-y-anova-de-1-factor-entre-sujetos"><i class="fa fa-check"></i><b>15.8.1</b> Relación entre la prueba <span class="math inline">\(t\)</span> de 2 muestras independientes y ANOVA de 1-factor entre-sujetos</a></li>
</ul></li>
<li class="chapter" data-level="15.9" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-pearson"><i class="fa fa-check"></i><b>15.9</b> Correlación de Pearson</a></li>
<li class="chapter" data-level="15.10" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-rpb"><i class="fa fa-check"></i><b>15.10</b> Correlación Punto Biserial</a></li>
<li class="chapter" data-level="15.11" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-chi"><i class="fa fa-check"></i><b>15.11</b> <span class="math inline">\(\chi^2\)</span> para 1 varianza</a></li>
<li class="chapter" data-level="15.12" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-f"><i class="fa fa-check"></i><b>15.12</b> <span class="math inline">\(F\)</span> para 2 varianzas</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html"><i class="fa fa-check"></i><b>16</b> Estadística No Paramétrica</a><ul>
<li class="chapter" data-level="16.1" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#introducción-14"><i class="fa fa-check"></i><b>16.1</b> Introducción</a></li>
<li class="chapter" data-level="16.2" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#pruebas-noparam"><i class="fa fa-check"></i><b>16.2</b> Pruebas no-paramétricas</a></li>
<li class="chapter" data-level="16.3" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#ES-np"><i class="fa fa-check"></i><b>16.3</b> Tamaño del efecto</a></li>
<li class="chapter" data-level="16.4" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#pruebas-chi2-nominales"><i class="fa fa-check"></i><b>16.4</b> Pruebas <span class="math inline">\(\chi^2\)</span> (nominales)</a><ul>
<li class="chapter" data-level="16.4.1" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#prueba-chi-gof"><i class="fa fa-check"></i><b>16.4.1</b> Bondad de ajuste</a></li>
<li class="chapter" data-level="16.4.2" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#tab-contingencia"><i class="fa fa-check"></i><b>16.4.2</b> Tablas de Contingencia</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#pruebas-sobre-rangos-ordinales"><i class="fa fa-check"></i><b>16.5</b> Pruebas sobre rangos (ordinales)</a><ul>
<li class="chapter" data-level="16.5.1" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#prueba-wilcoxon"><i class="fa fa-check"></i><b>16.5.1</b> Rango con signo de Wilcoxon</a></li>
<li class="chapter" data-level="16.5.2" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#prueba-mwu"><i class="fa fa-check"></i><b>16.5.2</b> Suma de rangos de Wilcoxon / U de Mann-Whitney</a></li>
<li class="chapter" data-level="16.5.3" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#prueba-kruskal"><i class="fa fa-check"></i><b>16.5.3</b> Kruskal-Wallis</a></li>
<li class="chapter" data-level="16.5.4" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#prueba-spearman"><i class="fa fa-check"></i><b>16.5.4</b> Correlación de Spearman</a></li>
</ul></li>
<li class="chapter" data-level="16.6" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#bootstrap"><i class="fa fa-check"></i><b>16.6</b> Bootstrap (remuestreo)</a><ul>
<li class="chapter" data-level="16.6.1" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#infer"><i class="fa fa-check"></i><b>16.6.1</b> <em>infer</em></a></li>
<li class="chapter" data-level="16.6.2" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#rsample"><i class="fa fa-check"></i><b>16.6.2</b> <em>rsample</em></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="estadística-direccional.html"><a href="estadística-direccional.html"><i class="fa fa-check"></i><b>17</b> Estadística Direccional</a><ul>
<li class="chapter" data-level="17.1" data-path="estadística-direccional.html"><a href="estadística-direccional.html#introducción-15"><i class="fa fa-check"></i><b>17.1</b> Introducción</a></li>
<li class="chapter" data-level="17.2" data-path="estadística-direccional.html"><a href="estadística-direccional.html#representación-gráfica"><i class="fa fa-check"></i><b>17.2</b> Representación gráfica</a></li>
<li class="chapter" data-level="17.3" data-path="estadística-direccional.html"><a href="estadística-direccional.html#datos-circulares"><i class="fa fa-check"></i><b>17.3</b> Datos circulares</a><ul>
<li class="chapter" data-level="17.3.1" data-path="estadística-direccional.html"><a href="estadística-direccional.html#estadística-descriptiva"><i class="fa fa-check"></i><b>17.3.1</b> Estadística descriptiva</a></li>
<li class="chapter" data-level="17.3.2" data-path="estadística-direccional.html"><a href="estadística-direccional.html#estadística-inferencial"><i class="fa fa-check"></i><b>17.3.2</b> Estadística inferencial</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="estadística-direccional.html"><a href="estadística-direccional.html#datos-esféricos"><i class="fa fa-check"></i><b>17.4</b> Datos esféricos</a><ul>
<li class="chapter" data-level="17.4.1" data-path="estadística-direccional.html"><a href="estadística-direccional.html#estadística-descriptiva-1"><i class="fa fa-check"></i><b>17.4.1</b> Estadística descriptiva</a></li>
<li class="chapter" data-level="17.4.2" data-path="estadística-direccional.html"><a href="estadística-direccional.html#estadística-inferencial-1"><i class="fa fa-check"></i><b>17.4.2</b> Estadística inferencial</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="secuencias-de-datos.html"><a href="secuencias-de-datos.html"><i class="fa fa-check"></i><b>18</b> Secuencias de Datos</a></li>
<li class="chapter" data-level="19" data-path="geoestadística.html"><a href="geoestadística.html"><i class="fa fa-check"></i><b>19</b> Geoestadística</a></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Creado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Geología Numérica: Ciencia de Datos para Geociencias</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estadística-direccional" class="section level1">
<h1><span class="header-section-number">Capítulo 17</span> Estadística Direccional</h1>
<div id="introducción-15" class="section level2">
<h2><span class="header-section-number">17.1</span> Introducción</h2>
<p>Los temas que se han introducido hasta este punto van a servir de base para el poder analizar datos geológicos de una manera más estadística y cuantitativa, brindado apoyo sobre los resultados encontrados.</p>
<p>El tema de estadística direccional es uno de estos temas muy específicos del quehacer geológico, ya que son la base de una gran mayoría de los tipos de datos que se pueden recolectar tanto en el campo como en trabajo de oficina.</p>
<p>Los métodos y técnicas de análisis que se van a presentar y explicar en este capítulo se basan en capítulos de <span class="citation">Davis (<a href="#ref-davis2002">2002</a>)</span>, <span class="citation">Swan &amp; Sandilands (<a href="#ref-swan1995">1995</a>)</span>, <span class="citation">Borradaile (<a href="#ref-borradaile2003">2003</a>)</span>, <span class="citation">Trauth (<a href="#ref-trauth2015">2015</a>)</span>, y <span class="citation">McKillup &amp; Darby Dyar (<a href="#ref-mckillup2010">2010</a>)</span>, y en los textos más exhaustivos de <span class="citation">Fisher et al. (<a href="#ref-fisher1993">1993</a>)</span> y <span class="citation">Mardia &amp; Jupp (<a href="#ref-mardia2000">2000</a>)</span>.</p>
<p>Es necesario hacer la distinción entre datos direccionales y no-direccionales (esta es la nomenclatura que se va a utilizar en este libro):</p>
<ul>
<li>Direccionales: tienen una dirección específica (polaridad), apuntan en una sola dirección. Pueden ser líneas o planos, aunque generalmente se asocian más con líneas.</li>
<li>No-direccionales: apuntan en dos direcciones a 180° una de la otra, no tienen dirección específica (polaridad). Pueden ser líneas o planos, aunque generalmente se asocian más con planos.</li>
</ul>
<p>No hay realmente un consenso de la nomenclatura. Algunos los llaman también direccionales y orientados, otros unidireccionales y bidireccionales, y otros tratan orientaciones desde otra perspectiva.</p>
<p>Ejemplos de estos tipos de datos serían:</p>
<ul>
<li>Estrías (direccionales)
<ul>
<li>Planos de falla</li>
<li>Glaciares</li>
</ul></li>
<li>Paleomagnetismo (direccionales)</li>
<li>Forma y orientación de ejes de granos en sección delgada (ambos)</li>
<li>Paleocorrientes (ambos)
<ul>
<li>Fósiles alineados (direccionales)</li>
<li>Clastos orientados (direccionales)</li>
<li>Ripples simétricos (no-direccionales)</li>
<li>Ripples asimétricos (direccionales)</li>
</ul></li>
<li>Dirección de buzamiento (direccionales)
<ul>
<li>Fallas</li>
<li>Capas</li>
<li>Pliegues</li>
</ul></li>
<li>Dirección de rumbo (no-direccionales)
<ul>
<li>Fallas</li>
<li>Capas</li>
<li>Pliegues</li>
</ul></li>
<li>Lineamientos regionales (no-direccionales)</li>
</ul>
<p>También se tiene que hacer distinción entre datos circulares y esféricos, donde la diferencia es que circulares se refieren a datos en 2-dimensiones (solo dirección), mientras que esféricos se refieren a datos en 3-dimensiones (dirección e inclinación). Una característica de los datos direccionales es la naturaleza del espacio en que se trabajan, que para direcciones va de 0° a 360° y para inclinaciones va de 0° a 90°. Esta particularidad hace que se tengan que tratar de manera especial, ajustando las técnicas convencionales a este tipo de datos.</p>
<p>Cabe mencionar que hay programas libres multi-plataforma que brindan mucha de la funcionalidad que se va a presentar en este capítulo, y representan buenas opciones y herramientas a tener en cuenta. Dentro de estos programas están: <a href="http://www.geo.cornell.edu/geology/faculty/RWA/programs/stereonet.html">Stereonet</a>, <a href="http://www.frederickvollmer.com/orient/">Orient</a>, y <a href="http://igc.usp.br/openstereo/">OpenStereo</a>.</p>
</div>
<div id="representación-gráfica" class="section level2">
<h2><span class="header-section-number">17.2</span> Representación gráfica</h2>
<p>Así como para visualizar una variable se tiene el histograma, para datos direccionales se tiene el <em>diagrama de rosa</em>, que es simplemente un histograma e coordenadas polares, como se muestra en la Figura <a href="estadística-direccional.html#fig:rose-diags-circ">17.1</a>, donde la rosa para datos direccionales se denomina rosa asimétrica, y para datos no-direccionales se denomina rosa simétrica.</p>

<div class="figure" style="text-align: center"><span id="fig:rose-diags-circ"></span>
<img src="geolonum_files/figure-html/rose-diags-circ-1.png" alt="Diagramas de rosa para el caso de datos direccionales (A - rosa asimétrica) y no-direccionales (B - rosa simétrica)." width="80%" />
<p class="caption">
Figura 17.1: Diagramas de rosa para el caso de datos direccionales (<strong>A</strong> - rosa asimétrica) y no-direccionales (<strong>B</strong> - rosa simétrica).
</p>
</div>
<p>El diagrama puede ser engañoso, debido a que el ancho y el área de cada segmento del arco incrementa con la distancia desde el origen. Si solo la longitud del pétalo es proporcional a la frecuencia la percepción de frecuencias bajas se verá disminuida y la de frecuencias altas se verá aumentada. Por ésto, los diagramas deben ser hechos con el área del pétalo proporcional a la frecuencia. Un ejemplo de esta distorsión es proporcionado por <span class="citation">Davis (<a href="#ref-davis2002">2002</a>)</span>, y se muestra en la Figura <a href="estadística-direccional.html#fig:rose-area">17.2</a>.</p>

<div class="figure" style="text-align: center"><span id="fig:rose-area"></span>
<img src="images/rose-diag-area.png" alt="Figura de Davis (2002) donde se muestra el efecto de utilizar la longitud del pétalo proporcional a la frecuencia (a), o el área del pétalo proporcional a la frecuencia (b), siendo esta última la adecuada." width="70%" />
<p class="caption">
Figura 17.2: Figura de <span class="citation">Davis (<a href="#ref-davis2002">2002</a>)</span> donde se muestra el efecto de utilizar la longitud del pétalo proporcional a la frecuencia (<em>a</em>), o el área del pétalo proporcional a la frecuencia (<em>b</em>), siendo esta última la adecuada.
</p>
</div>
</div>
<div id="datos-circulares" class="section level2">
<h2><span class="header-section-number">17.3</span> Datos circulares</h2>
<p>Se describen métodos de análisis para datos circulares (2D), donde se tiene por muestra 1 vector de datos (direcciones).</p>
<div id="estadística-descriptiva" class="section level3">
<h3><span class="header-section-number">17.3.1</span> Estadística descriptiva</h3>
<p>Cuando se tiene un conjunto de datos direccionales (<span class="math inline">\(\theta_1,\theta_2,\theta_3,\dots,\theta_N\)</span>), se pueden obtener estadísticas univariables que describen a la muestra.</p>
<p>Para obtener la dirección media y la longitud de la resultante, es necesario calcular las componentes mostradas en las Ecuaciones <a href="estadística-direccional.html#eq:xr-circ">(17.1)</a> y <a href="estadística-direccional.html#eq:yr-circ">(17.2)</a>.</p>
<p><span class="math display" id="eq:xr-circ">\[\begin{equation}
  x_r = \sum_{i=1}^N \sin\theta_i
  \tag{17.1}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:yr-circ">\[\begin{equation}
  y_r = \sum_{i=1}^N \cos\theta_i
  \tag{17.2}
\end{equation}\]</span></p>
<p>La dirección media (<span class="math inline">\(\bar{\theta}\)</span>) y longitud de la resultante (<span class="math inline">\(R\)</span>) se obtienen con las Ecuaciones <a href="estadística-direccional.html#eq:dir-media-circ">(17.3)</a> y <a href="estadística-direccional.html#eq:resultante-circ">(17.4)</a>.</p>
<p><span class="math display" id="eq:dir-media-circ">\[\begin{equation}
  \bar{\theta} = \tan^{-1}(x_r/y_r)
  \tag{17.3}
\end{equation}\]</span></p>
<p>Dada la naturaleza cíclica de los datos (0-360) el valor de la dirección media requiere de una corrección que va a estar en función del signo de las componentes, y se detalla en la Tabla <a href="estadística-direccional.html#tab:dir-media-ajuste-circ">17.1</a>.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:dir-media-ajuste-circ">Tabla 17.1: </span>Ajustes para la dirección media
</caption>
<thead>
<tr>
<th style="text-align:center;">
<span class="math inline">\(x_r\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(y_r\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(\bar{\theta}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Positivo
</td>
<td style="text-align:center;">
Positivo
</td>
<td style="text-align:center;">
<span class="math inline">\(\bar{\theta}\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
Negativo
</td>
<td style="text-align:center;">
Negativo
</td>
<td style="text-align:center;">
<span class="math inline">\(\bar{\theta}\)</span>+180
</td>
</tr>
<tr>
<td style="text-align:center;">
Negativo
</td>
<td style="text-align:center;">
Positivo
</td>
<td style="text-align:center;">
<span class="math inline">\(\bar{\theta}\)</span>+360
</td>
</tr>
</tbody>
</table>
<p><span class="math display" id="eq:resultante-circ">\[\begin{equation}
  R = \sqrt{x_r^2+y_r^2}
  \tag{17.4}
\end{equation}\]</span></p>
<p>La longitud de la resultante depende de la cantidad de datos. Para contrarrestar ésto y para comparar resultantes de diferentes muestras, con diferente número de mediciones, se debe estandarizar la longitud resultante, mostrada en la Ecuación <a href="estadística-direccional.html#eq:resultante-media-circ">(17.5)</a>, brindando la resultante media (<span class="math inline">\(\bar{R}\)</span>), la cual va a tener el rango de 0 a 1.</p>
<p><span class="math display" id="eq:resultante-media-circ">\[\begin{equation}
  \bar{R} = R/N
  \tag{17.5}
\end{equation}\]</span></p>
<p>La resultante media es una indicación de la dispersión de los datos, conforme más cercana a 1 más concentrados y conforme más cercana a 0 más dispersos. Por ésto es que se relaciona con la varianza circular (<span class="math inline">\(s_0\)</span>), conforme la Ecuación <a href="estadística-direccional.html#eq:s0">(17.6)</a>.</p>
<p><span class="math display" id="eq:s0">\[\begin{equation}
  s_0^2 = 1 - \bar{R} = (N-R)/N
  \tag{17.6}
\end{equation}\]</span></p>
<p>Para el caso de datos no-direccionales es necesario transformar los datos (duplicar los ángulos) a direccionales para poder calcularle las estadísticas, ésto porque se si calculan las estadísticas sobre los datos sin transformar se van a obtener resultados incorrectos y sin sentido. Después de obtener las estadísticas es necesario dividir la dirección media entre 2 para re-transformar los datos a las direcciones originales. Este concepto se puede visualizar en la Figura <a href="estadística-direccional.html#fig:krumbein">17.3</a>, donde la flecha indica la dirección media; se observa como cuando no se corrigen los datos (<em>a</em>) se obtiene una dirección media que no coincide con los datos, pero cuando se transforman (<em>b</em>) y se re-transforman (<em>c</em>) ahora sí la dirección media coincide y tiene sentido con los datos.</p>

<div class="figure" style="text-align: center"><span id="fig:krumbein"></span>
<img src="images/krumbein.png" alt="Demostración del efecto de no transformar los datos (a), transformación (b) y re-transformación (c), en la obtención de una dirección media (flecha) apropiada. Tomado de Davis (2002)." width="70%" />
<p class="caption">
Figura 17.3: Demostración del efecto de no transformar los datos (<em>a</em>), transformación (<em>b</em>) y re-transformación (<em>c</em>), en la obtención de una dirección media (flecha) apropiada. Tomado de <span class="citation">Davis (<a href="#ref-davis2002">2002</a>)</span>.
</p>
</div>
<p>Para demostrar lo expuesto hasta este punto se va a utilizar un ejemplo de <span class="citation">Trauth (<a href="#ref-trauth2015">2015</a>)</span>, donde se tienen los siguientes datos:</p>
<pre class="sourceCode r"><code class="sourceCode r">theta0 =<span class="st"> </span><span class="kw">c</span>(<span class="dv">255</span>, <span class="dv">239</span>, <span class="dv">222</span>, <span class="dv">231</span>, <span class="dv">199</span>, <span class="dv">271</span>, <span class="dv">222</span>, <span class="dv">274</span>, <span class="dv">228</span>, 
           <span class="dv">246</span>, <span class="dv">177</span>, <span class="dv">199</span>, <span class="dv">257</span>, <span class="dv">201</span>, <span class="dv">237</span>, <span class="dv">209</span>, <span class="dv">216</span>, <span class="dv">180</span>, 
           <span class="dv">182</span>, <span class="dv">250</span>, <span class="dv">219</span>, <span class="dv">196</span>, <span class="dv">197</span>, <span class="dv">246</span>, <span class="dv">218</span>, <span class="dv">235</span>, <span class="dv">232</span>, 
           <span class="dv">243</span>, <span class="dv">232</span>, <span class="dv">180</span>, <span class="dv">231</span>, <span class="dv">254</span>, <span class="dv">242</span>, <span class="dv">149</span>, <span class="dv">212</span>, <span class="dv">210</span>, 
           <span class="dv">230</span>, <span class="dv">205</span>, <span class="dv">220</span>, <span class="dv">268</span>)</code></pre>
<p>Componentes:</p>
<p><span class="math display">\[\begin{equation}
  x_r = \sum_{i=1}^N \sin\theta_i = -24.38\\
  y_r = \sum_{i=1}^N \cos\theta_i = -25.94
\end{equation}\]</span></p>
<p>Dirección media:</p>
<p><span class="math display">\[\begin{equation}
  \bar{\theta} = \tan^{-1}(x_r/y_r) = \tan^{-1}(-24.38/-25.94) = 43.22^{\circ}\\
  \text{Como } x \text{ y } y \text{ son negativas hay que agregar } 180^{\circ}\\
  \bar{\theta} = 43.22^{\circ} + 180^{\circ} = 223.22^{\circ}
\end{equation}\]</span></p>
<p>La resultante y resultante media:</p>
<p><span class="math display">\[\begin{equation}
  R = \sqrt{x_r^2+y_r^2} = \sqrt{-23.38^2+-25.94^2} = 35.61\\
  \bar{R} = R/N = 35.61/40 = .89
\end{equation}\]</span></p>
<p>La varianza circular:</p>
<p><span class="math display">\[\begin{equation}
  s_0^2 = 1 - \bar{R} = 1 - .89 = .11
\end{equation}\]</span></p>
<p>En <strong>R</strong> se pueden simplemente programar estas funciones ya que son sencillas, pero el paquete <em>GMisc</em> <span class="citation">(Garnier-Villarreal, <a href="#ref-R-GMisc">2020</a>)</span> tiene la función <code>dir_stats_2D</code> que calcula éstos y otros valores que se van a exponer más adelante. Primero se muestra el paso a paso y luego se usa la función mencionada. Muchas de las funciones de <em>GMisc</em> tienen el argumento <code>dir</code>, donde 1 representa datos direccionales y 0 datos no-direccionales.</p>
<p>Componentes:</p>
<pre class="sourceCode r"><code class="sourceCode r">(<span class="dt">x =</span> <span class="kw">sum</span>(<span class="kw">sin</span>(<span class="kw">rads</span>(theta0))))</code></pre>
<pre><code>## [1] -24.38979</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">(<span class="dt">y =</span> <span class="kw">sum</span>(<span class="kw">cos</span>(<span class="kw">rads</span>(theta0))))</code></pre>
<pre><code>## [1] -25.94007</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">meanrad =<span class="st"> </span><span class="kw">atan</span>(x<span class="op">/</span>y) <span class="co"># direccion media en radianes</span>
(<span class="dt">meandeg =</span> <span class="kw">degs</span>(meanrad)) <span class="co"># direccion media en grados</span></code></pre>
<pre><code>## [1] 43.23571</code></pre>
<p>Dirección media:</p>
<pre class="sourceCode r"><code class="sourceCode r">meantrue =<span class="st"> </span><span class="kw">case_when</span>(x <span class="op">&amp;</span><span class="st"> </span>y <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span> <span class="op">~</span><span class="st"> </span>meandeg,
                     x <span class="op">&amp;</span><span class="st"> </span>y <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span> <span class="op">~</span><span class="st"> </span>meandeg <span class="op">+</span><span class="st"> </span><span class="dv">180</span>,
                     T <span class="op">~</span><span class="st"> </span>meandeg <span class="op">+</span><span class="st"> </span><span class="dv">360</span>)
meantrue</code></pre>
<pre><code>## [1] 223.2357</code></pre>
<p>La resultante media y varianza circular:</p>
<pre class="sourceCode r"><code class="sourceCode r">(<span class="dt">R =</span> <span class="kw">sqrt</span>(x<span class="op">^</span><span class="dv">2</span><span class="op">+</span>y<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span><span class="kw">length</span>(theta0)) <span class="co"># resultante media</span></code></pre>
<pre><code>## [1] 0.8901366</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">(<span class="dt">s0 =</span> <span class="dv">1</span><span class="op">-</span>R) <span class="co"># varianza circular</span></code></pre>
<pre><code>## [1] 0.1098634</code></pre>
<p>Usando <code>dir_stats_2D</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r">a =<span class="st"> </span><span class="fl">.05</span>
<span class="kw">dir_stats_2D</span>(theta0, <span class="dt">dir =</span> <span class="dv">1</span>, <span class="dt">conf.level =</span> <span class="dv">1</span><span class="op">-</span>a)</code></pre>
<pre><code>## # A tibble: 1 x 7
##   Mean.Dir     R Circ.Var Conc.Param Cone.lower Cone.upper  Cone
##      &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;
## 1     223.  0.89     0.11       4.85       215.       232.  8.55</code></pre>
<p>El diagrama de rosa se puede generar con la función <code>rose_diag_2D</code> de <em>GMisc</em>, donde el argumento <code>width</code> corresponde con el ancho del pétalo.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rose_diag_2D</span>(theta0, <span class="dt">width =</span> <span class="dv">30</span>, <span class="dt">dir =</span> <span class="dv">1</span>, <span class="dt">conf.level =</span> <span class="dv">1</span><span class="op">-</span>a)</code></pre>
<p><img src="geolonum_files/figure-html/unnamed-chunk-198-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>Un ejemplo de datos no-direccionales corresponde con los datos <code>carolina</code>, disponibles en el paquete <em>GMisc</em>, tomados de <span class="citation">Davis (<a href="#ref-davis2002">2002</a>)</span>. El cuidado que hay que tener es duplicar los datos antes de los cálculos, y cuando se calcula la dirección media (la que se llamó <code>meantrue</code>) hay que dividirla entre 2.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dir_stats_2D</span>(carolina, <span class="dt">dir =</span> <span class="dv">0</span>, <span class="dt">conf.level =</span> <span class="dv">1</span><span class="op">-</span>a)</code></pre>
<pre><code>## # A tibble: 1 x 7
##   Mean.Dir     R Circ.Var Conc.Param Cone.lower Cone.upper  Cone
##      &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;
## 1     48.7 0.982   0.0177       28.5       47.6       49.8  1.07</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rose_diag_2D</span>(carolina, <span class="dt">width =</span> <span class="dv">20</span>, <span class="dt">dir =</span> <span class="dv">0</span>, <span class="dt">conf.level =</span> <span class="dv">1</span><span class="op">-</span>a)</code></pre>
<p><img src="geolonum_files/figure-html/unnamed-chunk-200-1.png" width="70%" style="display: block; margin: auto;" /></p>
</div>
<div id="estadística-inferencial" class="section level3">
<h3><span class="header-section-number">17.3.2</span> Estadística inferencial</h3>
<p>Así como para datos convencionales (<span class="math inline">\(-∞,∞\)</span>) se tenía la distribución normal (o <span class="math inline">\(t\)</span>) para hacer inferencias, se ocupa una distribución apropiada para datos circulares. Esta distribución es la <em>von Mises</em> (Figura <a href="estadística-direccional.html#fig:von-mises">17.4</a>) y depende de 2 parámetros: dirección media (<span class="math inline">\(\theta\)</span>) y el parámetro de concentración (<span class="math inline">\(\kappa\)</span>). Esta distribución es unimodal y simétrica alrededor de <span class="math inline">\(\theta\)</span>, y conforme <span class="math inline">\(\kappa\)</span> incrementa es más probable que los datos tengan una dirección preferencial cercana <span class="math inline">\(\theta\)</span>. De manera general se relaciona <span class="math inline">\(\kappa\)</span> con <span class="math inline">\(\bar{R}\)</span>.</p>

<div class="figure" style="text-align: center"><span id="fig:von-mises"></span>
<img src="images/von-mises.png" alt="Distribución von Mises centrada en \(\theta=0\) y con diferentes parámetros de concentración \(\kappa\). Conforme incrementa \(\kappa\) más probabilidad de estar cerca de \(\theta\). \(\kappa=0\) es igual a una distribución uniforme. Tomado de Trauth (2015)." width="70%" />
<p class="caption">
Figura 17.4: Distribución <em>von Mises</em> centrada en <span class="math inline">\(\theta=0\)</span> y con diferentes parámetros de concentración <span class="math inline">\(\kappa\)</span>. Conforme incrementa <span class="math inline">\(\kappa\)</span> más probabilidad de estar cerca de <span class="math inline">\(\theta\)</span>. <span class="math inline">\(\kappa=0\)</span> es igual a una distribución uniforme. Tomado de <span class="citation">Trauth (<a href="#ref-trauth2015">2015</a>)</span>.
</p>
</div>
<div id="prueba-de-aleatoriedad" class="section level4">
<h4><span class="header-section-number">17.3.2.1</span> Prueba de aleatoriedad</h4>
<p>Esta prueba, conocida también como la prueba de Rayleigh, es para determinar si los datos presentan una dirección preferencial o no, y se aplica por medio de la relación entre <span class="math inline">\(\kappa\)</span> y <span class="math inline">\(\bar{R}\)</span>, donde las hipótesis nula y alterna serían las siguientes:</p>
<ul>
<li><span class="math inline">\(H_0: \kappa = 0 \to\)</span> No hay dirección preferencial</li>
<li><span class="math inline">\(H_1: \kappa \neq 0 \to\)</span> Hay dirección preferencial</li>
</ul>
<p>Como se basa en la relación entre <span class="math inline">\(\kappa\)</span> y <span class="math inline">\(\bar{R}\)</span>, lo que se hace es determinar <span class="math inline">\(\bar{R}\)</span> y compararlo con valores críticos ya establecidos en función del tamaño de la muestra <span class="math inline">\(N\)</span>, y si <span class="math inline">\(\bar{R} &gt; \bar{R}_{crit}\)</span> entonces e rechazaría <span class="math inline">\(H_0\)</span>. Los valores críticos se encuentran en tablas en los diferentes textos. Para el caso de datos no-direccionales no es necesario realizar ninguna corrección más que la inicial para encontrar <span class="math inline">\(\bar{R}\)</span>.</p>
<p>Para el caso del ejemplo que se venía trabajando en la parte descriptiva, se tiene <span class="math inline">\(\bar{R}_{crit}=\bar{R}_{40,.05}=.273\)</span> y se tenía que <span class="math inline">\(\bar{R}=.89\)</span>, con lo que <span class="math inline">\(\bar{R} &gt; \bar{R}_{crit}\)</span> y se rechaza la hipótesis nula de que no hay dirección preferencial, y en este caso corresponde con <span class="math inline">\(\bar{\theta}=223.22^{\circ}\)</span>.</p>
<p>En <strong>R</strong> se tiene la función <code>dir_unif_test_2D</code> del paquete <em>GMisc</em> que arroja los valores <span class="math inline">\(\bar{R}\)</span> y <span class="math inline">\(\bar{R}_{crit}\)</span>, y una breve interpretación.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dir_unif_test_2D</span>(theta0, <span class="dt">dir =</span> <span class="dv">1</span>, <span class="dt">conf.level =</span> <span class="dv">1</span><span class="op">-</span>a)</code></pre>
<pre><code>## $R
## [1] 0.89
## 
## $Rcrit
## [1] 0.273
## 
## $interpretation
## [1] &quot;Reject H0 and conclude that the sample has a preferred mean direction&quot;</code></pre>
<blockquote>
<p>Conclusión: La muestra presenta una direccional preferencial, <span class="math inline">\(\bar{\theta}=223.22^{\circ}\)</span>, <span class="math inline">\(\bar{R}=.89\)</span>.</p>
</blockquote>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dir_unif_test_2D</span>(carolina, <span class="dt">dir =</span> <span class="dv">0</span>, <span class="dt">conf.level =</span> <span class="dv">1</span><span class="op">-</span>a)</code></pre>
<pre><code>## $R
## [1] 0.982
## 
## $Rcrit
## [1] 0.175
## 
## $interpretation
## [1] &quot;Reject H0 and conclude that the sample has a preferred mean direction&quot;</code></pre>
</div>
<div id="prueba-de-tendencia-específica" class="section level4">
<h4><span class="header-section-number">17.3.2.2</span> Prueba de tendencia específica</h4>
<p>Esta prueba es homóloga a la prueba <span class="math inline">\(t\)</span> de una muestra, ya que quiere probar si las mediciones corresponden con una dirección específica. No hay una prueba <em>per se</em>, sino lo que se hace es calcular un cono de confianza alrededor de la dirección media de la muestra y ver si la dirección a la cual se quiere comparar cae dentro de este ángulo, similar a usar intervalos de confianza en estadística clásica.</p>
<p>Las hipótesis nula y alterna serían las siguientes:</p>
<ul>
<li><span class="math inline">\(H_0: \bar{\theta} = \theta_0\)</span></li>
<li><span class="math inline">\(H_1: \bar{\theta} \neq \theta_0\)</span></li>
</ul>
<p>El cono de confianza, Ecuación <a href="estadística-direccional.html#eq:cono-conf-circ">(17.9)</a>, se basa en el error estándar de la dirección media, Ecuación <a href="estadística-direccional.html#eq:se-theta-circ">(17.8)</a>, y por ende toma en cuenta el tamaño de la muestra y su dispersión. El error estándar resulta en <strong>radianes</strong>, por lo que hay que pasarlo a grados multiplicando por 57.2956. El parámetro de concentración <span class="math inline">\(\kappa\)</span> se puede obtener conforme la Ecuación <a href="estadística-direccional.html#eq:kappa-circ">(17.7)</a>.</p>
<p><span class="math display" id="eq:kappa-circ">\[\begin{equation}
  \kappa = 
  \begin{cases}
  \frac{\bar{R}}{6}\left( 12 + 6\bar{R}^2 + 5\bar{R}^4 \right) &amp; \text{si } \bar{R} &lt; .65\\
  \frac{1}{\left( 2 (1-\bar{R}) - (1-\bar{R})^2 - (1-\bar{R})^3 \right)} &amp; \text{si } \bar{R} &gt; .65
  \end{cases}
  \tag{17.7}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:se-theta-circ">\[\begin{equation}
  s_e = 1 / \sqrt{N \bar{R} \kappa}
  \tag{17.8}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:cono-conf-circ">\[\begin{equation}
  \bar{\theta} \pm z_{\alpha/2} s_e
  \tag{17.9}
\end{equation}\]</span></p>
<p>donde <span class="math inline">\(z_{\alpha/2}\)</span> corresponde con el valor crítico de la curva normal estándar usada en las pruebas estadísticas convencionales.</p>
<p>De nuevo, si se están trabajando con datos no-direccionales hay que dividir el error estándar entre 2 para volverlo a la dirección original.</p>
<p>En <strong>R</strong> se pueden programar las ecuaciones:</p>
<pre class="sourceCode r"><code class="sourceCode r">(<span class="dt">k =</span> <span class="kw">ifelse</span>(R<span class="op">&lt;</span><span class="fl">0.65</span>, 
            R<span class="op">/</span><span class="dv">6</span><span class="op">*</span>(<span class="dv">12</span><span class="op">+</span><span class="dv">6</span><span class="op">*</span>R<span class="op">^</span><span class="dv">2</span><span class="op">+</span><span class="dv">5</span><span class="op">*</span>R<span class="op">^</span><span class="dv">4</span>), 
            <span class="dv">1</span><span class="op">/</span>(<span class="dv">2</span><span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>R)<span class="op">-</span>(<span class="dv">1</span><span class="op">-</span>R)<span class="op">^</span><span class="dv">2</span><span class="op">-</span>(<span class="dv">1</span><span class="op">-</span>R)<span class="op">^</span><span class="dv">3</span>)))</code></pre>
<pre><code>## [1] 4.846588</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">se =<span class="st"> </span>(<span class="dv">1</span><span class="op">/</span><span class="kw">sqrt</span>(<span class="kw">length</span>(theta0)<span class="op">*</span>R<span class="op">*</span>k))<span class="op">*</span><span class="dv">180</span><span class="op">/</span>pi
(<span class="dt">cono =</span> <span class="kw">qnorm</span>(<span class="dv">1</span><span class="op">-</span>a<span class="op">/</span><span class="dv">2</span>)<span class="op">*</span>se)</code></pre>
<pre><code>## [1] 8.548587</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">cono_sup =<span class="st"> </span>meantrue <span class="op">+</span><span class="st"> </span>cono
cono_inf =<span class="st"> </span>meantrue <span class="op">-</span><span class="st"> </span>cono
cono_inf; meantrue; cono_sup</code></pre>
<pre><code>## [1] 214.6871</code></pre>
<pre><code>## [1] 223.2357</code></pre>
<pre><code>## [1] 231.7843</code></pre>
<p>El cono y cono de confianza se incluye en el resultado de <code>dir_stats_2D</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dir_stats_2D</span>(theta0, <span class="dt">dir =</span> <span class="dv">1</span>, <span class="dt">conf.level =</span> <span class="dv">1</span><span class="op">-</span>a)</code></pre>
<pre><code>## # A tibble: 1 x 7
##   Mean.Dir     R Circ.Var Conc.Param Cone.lower Cone.upper  Cone
##      &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;
## 1     223.  0.89     0.11       4.85       215.       232.  8.55</code></pre>
<blockquote>
<p>Conclusión: La muestra pudo provenir de una población con dirección <span class="math inline">\(214.7^{\circ} &lt; \bar{\theta} &lt; 231.8^{\circ}\)</span>.</p>
</blockquote>
</div>
<div id="prueba-de-igualdad-entre-dos-muestras" class="section level4">
<h4><span class="header-section-number">17.3.2.3</span> Prueba de igualdad entre dos muestras</h4>
<p>Esta prueba es homóloga a la prueba <span class="math inline">\(t\)</span> de dos muestras independientes, y se denomina prueba de Watson-Williams. La idea es determinar si dos muestras de mediciones poseen una misma dirección media. Se hace comparando las longitudes resultantes de los 2 grupos con la longitud resultante cuando se combinan los 2 grupos de mediciones. Si las dos muestras provienen de la misma población la longitud resultante de la combinación de los 2 grupos debiera ser igual a la suma de las dos resultantes. Si las direcciones medias son significativamente diferentes, la resultante combinada va a ser menor que la suma de las dos resultantes.</p>
<p>Las hipótesis nula y alterna serían las siguientes:</p>
<ul>
<li><span class="math inline">\(H_0: \bar{\theta}_1 = \bar{\theta}_2\)</span></li>
<li><span class="math inline">\(H_1: \bar{\theta}_1 \neq \bar{\theta}_2\)</span></li>
</ul>
<p>La prueba es una prueba <span class="math inline">\(F\)</span> con grados de libertad <span class="math inline">\(1\)</span> y <span class="math inline">\(N-2\)</span>. Al obtener la resultante combinada se estima un <span class="math inline">\(\kappa\)</span>, a partir de la magnitud de éste se usa la Ecuación <a href="estadística-direccional.html#eq:f-k-circ">(17.10)</a>.</p>
<p><span class="math display" id="eq:f-k-circ">\[\begin{equation}
  F_{1,N-2} = 
  \begin{cases}
  \frac{(N-2)(R_1+R_2-R_c)}{N-R_1-R_2} &amp; \text{si } \kappa &gt; 10\\
  \left(1+\frac{3}{8\kappa}\right)\frac{(N-2)(R_1+R_2-R_c)}{N-R_1-R_2} &amp; \text{si } 2 &lt; \kappa &lt; 10
  \end{cases}
  \tag{17.10}
\end{equation}\]</span></p>
<p>donde <span class="math inline">\(N\)</span> es el total de observaciones de las dos muestras, <span class="math inline">\(R_1\)</span> es la resultante de la muestra 1, <span class="math inline">\(R_2\)</span> es la resultante de la muestra 2, <span class="math inline">\(R_c\)</span> es la resultante combinando las dos muestras, <span class="math inline">\(\kappa\)</span> es el parámetro de concentración a partir de <span class="math inline">\(R_c\)</span>.</p>
<p>Para demostrar esta prueba se tienen otros datos direccionales <span class="citation">(Trauth, <a href="#ref-trauth2015">2015</a>)</span> contra los cuales se quiere comparar los que se venían trabajando.</p>
<pre class="sourceCode r"><code class="sourceCode r">theta1 =<span class="st"> </span><span class="kw">c</span>(<span class="dv">225</span>, <span class="dv">208</span>, <span class="dv">172</span>, <span class="dv">198</span>, <span class="dv">204</span>, <span class="dv">183</span>, <span class="dv">190</span>, <span class="dv">212</span>, <span class="dv">247</span>, 
           <span class="dv">127</span>, <span class="dv">167</span>, <span class="dv">234</span>, <span class="dv">217</span>, <span class="dv">192</span>, <span class="dv">212</span>, <span class="dv">171</span>, <span class="dv">169</span>, <span class="dv">210</span>, 
           <span class="dv">245</span>, <span class="dv">222</span>, <span class="dv">185</span>, <span class="dv">227</span>, <span class="dv">193</span>, <span class="dv">178</span>, <span class="dv">187</span>, <span class="dv">182</span>, <span class="dv">194</span>, 
           <span class="dv">217</span>, <span class="dv">168</span>, <span class="dv">211</span>, <span class="dv">234</span>, <span class="dv">204</span>, <span class="dv">221</span>, <span class="dv">198</span>, <span class="dv">261</span>, <span class="dv">228</span>, 
           <span class="dv">146</span>, <span class="dv">201</span>, <span class="dv">146</span>, <span class="dv">231</span>)</code></pre>
<p>Con estos datos se tiene <span class="math inline">\(R_2=35.26\)</span>, y se tenía <span class="math inline">\(R_1=35.61\)</span>, con lo que <span class="math inline">\(R_c=69.51\)</span>, y ahora <span class="math inline">\(N=80\)</span>. <span class="math inline">\(\bar{R}_c=R_c/N=69.51/80=.8689\)</span> y con ésto se tiene <span class="math inline">\(\kappa=4.18\)</span>, con lo que <span class="math inline">\(2 &lt; \kappa &lt; 10\)</span>.</p>
<p><span class="math display">\[\begin{equation}
  F_{1,N-2} = \left(1+\frac{3}{8\kappa}\right)\frac{(N-2)(R_1+R_2-R_c)}{N-R_1-R_2}\\
  F_{1,78} = \left(1+\frac{3}{8\cdot4.18}\right)\frac{(78)(35.61+35.26-69.51)}{80-35.61-35.26} = 12.58\\
  F_{1,78,.05} = 3.96 \to F &gt; F_{crit}, \text{se rechaza } H_0
\end{equation}\]</span></p>
<p>La función <code>dir_2sample_test_2D</code> de <em>GMisc</em> realiza esta prueba, brindando <span class="math inline">\(F\)</span>, <span class="math inline">\(F_{crit}\)</span>, valor-<em>p</em>, y una interpretación.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dir_2sample_test_2D</span>(theta0, theta1,
                    <span class="dt">dir =</span> <span class="dv">1</span>, <span class="dt">conf.level =</span> <span class="dv">1</span><span class="op">-</span>a)</code></pre>
<pre><code>## $f
## [1] 12.26
## 
## $fcrit
## [1] 3.96
## 
## $p_value
## [1] 0.000768
## 
## $interpretation
## [1] &quot;Reject H0 and conclude that the two samples could not come from the same population with the same mean direction&quot;</code></pre>
<blockquote>
<p>Conclusión: Las muestras difieren significativamente en su dirección, <span class="math inline">\(F(1,78) = 12.26\)</span>, <span class="math inline">\(p = .001\)</span></p>
</blockquote>
<p>Otra forma de realizar la prueba sería obtener los conos de confianza para ambas muestras y ver si la dirección media de una cae dentro del cono de la otra.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dir_stats_2D</span>(theta0, <span class="dt">dir =</span> <span class="dv">1</span>, <span class="dt">conf.level =</span> <span class="dv">1</span><span class="op">-</span>a)</code></pre>
<pre><code>## # A tibble: 1 x 7
##   Mean.Dir     R Circ.Var Conc.Param Cone.lower Cone.upper  Cone
##      &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;
## 1     223.  0.89     0.11       4.85       215.       232.  8.55</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dir_stats_2D</span>(theta1, <span class="dt">dir =</span> <span class="dv">1</span>, <span class="dt">conf.level =</span> <span class="dv">1</span><span class="op">-</span>a)</code></pre>
<pre><code>## # A tibble: 1 x 7
##   Mean.Dir     R Circ.Var Conc.Param Cone.lower Cone.upper  Cone
##      &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;
## 1     201. 0.881    0.119       4.52       192.       210.   8.9</code></pre>
<p>Lo anterior se puede visualizar en una red estereográfica, que por tratarse de datos circulares (2D) se usa una inclinación de 0. La función <code>stereo_mean</code> de <em>GMisc</em> permite graficar la dirección media junto con el cono de confianza en la red estereográfica, donde la Figura <a href="estadística-direccional.html#fig:stereo-2-circ">17.5</a> muestra los datos del ejemplo.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">stereo_mean</span>(theta0,<span class="dv">0</span>)
<span class="kw">stereo_mean</span>(theta1,<span class="dv">0</span>,<span class="dt">mean.col =</span> <span class="st">&#39;blue&#39;</span>,<span class="dt">add =</span> T)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:stereo-2-circ"></span>
<img src="geolonum_files/figure-html/stereo-2-circ-1.png" alt="Red estereográfica mostrando la dirección media y cono de confianza para los datos del ejemplo de dos muestras de datos circulares. En rojo los datos de la muestra 1 y en azul los datos de la muestra 2." width="100%" />
<p class="caption">
Figura 17.5: Red estereográfica mostrando la dirección media y cono de confianza para los datos del ejemplo de dos muestras de datos circulares. En rojo los datos de la muestra 1 y en azul los datos de la muestra 2.
</p>
</div>
</div>
</div>
</div>
<div id="datos-esféricos" class="section level2">
<h2><span class="header-section-number">17.4</span> Datos esféricos</h2>
<p>Los datos esféricos (3D) van a estar representados por dos vectores: uno para direcciones y otro para inclinaciones. En este apartado, y en el libro en general, se van a trabar como datos direccionales únicamente, por lo que si se quieren analizar datos no-direccionales se recomienda pasarlos a direccionales, la única excepción es la confección del diagrama de rosa. Los métodos de análisis para datos esféricos son simplemente una expansión sobre los métodos para datos circulares.</p>
<div id="estadística-descriptiva-1" class="section level3">
<h3><span class="header-section-number">17.4.1</span> Estadística descriptiva</h3>
<p>Para datos esféricos se van a tener dos vectores de datos:</p>
<ul>
<li>Ángulo de inclinación: <span class="math inline">\(\theta_1,\theta_2,\theta_3,\dots,\theta_N\)</span>,</li>
<li>Dirección de inclinación: <span class="math inline">\(\phi_1,\phi_2,\phi_3,\dots,\phi_N\)</span></li>
</ul>
<p>Para obtener la dirección media y la longitud de la resultante, es necesario calcular las componentes mostradas en las Ecuaciones <a href="estadística-direccional.html#eq:xr-esf">(17.11)</a>, <a href="estadística-direccional.html#eq:yr-esf">(17.12)</a>, y <a href="estadística-direccional.html#eq:zr-esf">(17.13)</a>.</p>
<p><span class="math display" id="eq:xr-esf">\[\begin{equation}
  x_r = \sum_{i=1}^N \cos\theta_i \cos\phi_i
  \tag{17.11}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:yr-esf">\[\begin{equation}
  y_r = \sum_{i=1}^N \cos\theta_i \sin\phi_i
  \tag{17.12}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:zr-esf">\[\begin{equation}
  z_r = \sum_{i=1}^N \sin\theta_i
  \tag{17.13}
\end{equation}\]</span></p>
<p>La dirección media (<span class="math inline">\(\bar{\phi}\)</span>), inclinación media (<span class="math inline">\(\bar{\theta}\)</span>), y longitud de la resultante (<span class="math inline">\(R\)</span>) se obtienen con las Ecuaciones <a href="estadística-direccional.html#eq:dir-media-esf">(17.14)</a>, <a href="estadística-direccional.html#eq:inc-media-esf">(17.15)</a>, y <a href="estadística-direccional.html#eq:resultante-esf">(17.16)</a>. Hay que realizar un ajuste para la dirección media según la Tabla <a href="estadística-direccional.html#tab:dir-media-ajuste-esf">17.2</a>.</p>
<p><span class="math display" id="eq:dir-media-esf">\[\begin{equation}
  \bar{\phi} = \tan^{-1}(y_r/x_r)
  \tag{17.14}
\end{equation}\]</span></p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:dir-media-ajuste-esf">Tabla 17.2: </span>Ajustes para la dirección media
</caption>
<thead>
<tr>
<th style="text-align:center;">
<span class="math inline">\(y_r\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(x_r\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(\bar{\phi}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Positivo
</td>
<td style="text-align:center;">
Positivo
</td>
<td style="text-align:center;">
<span class="math inline">\(\bar{\phi}\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
Negativo
</td>
<td style="text-align:center;">
Negativo
</td>
<td style="text-align:center;">
<span class="math inline">\(\bar{\phi}\)</span>+180
</td>
</tr>
<tr>
<td style="text-align:center;">
Negativo
</td>
<td style="text-align:center;">
Positivo
</td>
<td style="text-align:center;">
<span class="math inline">\(\bar{\phi}\)</span>+360
</td>
</tr>
</tbody>
</table>
<p><span class="math display" id="eq:inc-media-esf">\[\begin{equation}
  \bar{\theta} = \sin^{-1}(z_r/R)
  \tag{17.15}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:resultante-esf">\[\begin{equation}
  R = \sqrt{x_r^2+y_r^2+z_r^2}
  \tag{17.16}
\end{equation}\]</span></p>
<p>La resultante media (<span class="math inline">\(\bar{R}\)</span>) se obtiene de la misma manera que para datos circulares, Ecuación <a href="estadística-direccional.html#eq:resultante-media-circ">(17.5)</a>.</p>
<p><span class="math display" id="eq:resultante-media-circ">\[\begin{equation}
  \bar{R} = R/N
  \tag{17.5}
\end{equation}\]</span></p>
<p>La varianza esférica (<span class="math inline">\(s_s\)</span>) de nuevo se relaciona con la resultante media, conforme la Ecuación <a href="estadística-direccional.html#eq:s-esf">(17.17)</a>.</p>
<p><span class="math display" id="eq:s-esf">\[\begin{equation}
  s_s^2 = 1 - \bar{R} = (N-R)/N
  \tag{17.17}
\end{equation}\]</span></p>
<p>El parámetro de concentración se determina mediante la Ecuación <a href="estadística-direccional.html#eq:kappa-esf">(17.18)</a>.</p>
<p><span class="math display" id="eq:kappa-esf">\[\begin{equation}
  \kappa = \frac{N-2}{N-R}
  \tag{17.18}
\end{equation}\]</span></p>
<p>Se demuestran estos conceptos con un ejemplo con los siguientes datos:</p>
<pre class="sourceCode r"><code class="sourceCode r">direcciones =<span class="st"> </span><span class="kw">c</span>(<span class="dv">12</span>,<span class="dv">18</span>,<span class="dv">22</span>,<span class="dv">15</span>,<span class="dv">10</span>,<span class="dv">20</span>) <span class="co"># phi</span>
inclinaciones =<span class="st"> </span><span class="kw">c</span>(<span class="dv">42</span>,<span class="dv">40</span>,<span class="dv">48</span>,<span class="dv">30</span>,<span class="dv">42</span>,<span class="dv">30</span>) <span class="co"># theta</span></code></pre>
<p>Con estos datos se tiene:</p>
<p><span class="math display">\[\begin{equation}
  N = 6\\
  x_r = \sum_{i=1}^N \cos\theta_i \cos\phi_i = 4.46\\
  y_r = \sum_{i=1}^N \cos\theta_i \sin\phi_i = 1.29\\
  z_r = \sum_{i=1}^N \sin\theta_i = 3.72\\
  R = \sqrt{x_r^2+y_r^2+z_r^2} = 5.95\\
  \bar{\phi} = \tan^{-1}(y_r/x_r) = 16.13^{\circ}\\
  \bar{\theta} = \sin^{-1}(z_r/R) = 38.7^{\circ}\\
  \bar{R} = R/N = .992\\
  s_s^2 = 1 - \bar{R} = (N-R)/N = .008\\
  \kappa = \frac{N-2}{N-R} = 80
\end{equation}\]</span></p>
<p>En <strong>R</strong> se pueden simplemente programar estas funciones ya que son sencillas, pero el paquete <em>GMisc</em> tiene la función <code>dir_stats_3D</code> que calcula éstos y otros valores que se van a exponer más adelante.</p>
<pre class="sourceCode r"><code class="sourceCode r">a =<span class="st"> </span><span class="fl">.05</span>
<span class="kw">dir_stats_3D</span>(<span class="dt">dir =</span> direcciones, <span class="dt">dip =</span> inclinaciones, <span class="dt">conf.level =</span> <span class="dv">1</span><span class="op">-</span>a)</code></pre>
<pre><code>## # A tibble: 1 x 8
##   Mean.Dir MeanDip     R Sph.Var Conc.Param Cone.lower Cone.upper  Cone
##      &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;
## 1     16.2    38.7 0.992 0.00821       81.2        9.5       22.8  6.68</code></pre>
<p>El diagrama de rosa se puede generar con la función <code>rose_diag_3D</code> de <em>GMisc</em>, donde el argumento <code>width</code> corresponde con el ancho del pétalo.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rose_diag_3D</span>(<span class="dt">az =</span> direcciones, <span class="dt">dip =</span> inclinaciones, 
             <span class="dt">width =</span> <span class="dv">20</span>, <span class="dt">dir =</span> <span class="dv">1</span>, <span class="dt">conf.level =</span> <span class="dv">1</span><span class="op">-</span>a)</code></pre>
<p><img src="geolonum_files/figure-html/unnamed-chunk-210-1.png" width="70%" style="display: block; margin: auto;" /></p>
</div>
<div id="estadística-inferencial-1" class="section level3">
<h3><span class="header-section-number">17.4.2</span> Estadística inferencial</h3>
<p>Similar a los datos circulares es necesaria una distribución para poder realizar inferencias, y para el caso de datos esféricos la más común es la Bingham. Esta distribución depende de tres parámetros: dirección media (<span class="math inline">\(\bar{\phi}\)</span>), inclinación media (<span class="math inline">\(\bar{\theta}\)</span>), y parámetro de concentración (<span class="math inline">\(\kappa\)</span>). El parámetro de concentración presenta el mismo efecto y comportamiento que el caso de dato circulares, dígase que se relaciona con <span class="math inline">\(\bar{R}\)</span> y conforme incrementa es más probable que los datos tengan una dirección preferencial.</p>
<div id="prueba-de-aleatoriedad-1" class="section level4">
<h4><span class="header-section-number">17.4.2.1</span> Prueba de aleatoriedad</h4>
<p>Esta prueba es similar a la de datos circulares, donde se usa la relación entre <span class="math inline">\(\kappa\)</span> y <span class="math inline">\(\bar{R}\)</span>, y donde las hipótesis nula y alterna serían las siguientes:</p>
<ul>
<li><span class="math inline">\(H_0: \kappa = 0 \to\)</span> No hay dirección preferencial</li>
<li><span class="math inline">\(H_1: \kappa \neq 0 \to\)</span> Hay dirección preferencial</li>
</ul>
<p>El procedimiento es el mismo a la prueba para datos circulares pero los valores críticos <span class="math inline">\(\bar{R}_{crit}\)</span> son ahora para datos esféricos.</p>
<p>Para el caso del ejemplo, se tiene <span class="math inline">\(\bar{R}_{crit}=\bar{R}_{6,.05}=.642\)</span> y se tenía que <span class="math inline">\(\bar{R}=.992\)</span>, con lo que <span class="math inline">\(\bar{R} &gt; \bar{R}_{crit}\)</span> y se rechaza la hipótesis nula de que no hay dirección preferencial, y en este caso corresponde con <span class="math inline">\(\phi=16.13^{\circ}\)</span>.</p>
<p>En <strong>R</strong> se tiene la función <code>dir_unif_test_3D</code> del paquete <em>GMisc</em> que arroja los valores <span class="math inline">\(\bar{R}\)</span> y <span class="math inline">\(\bar{R}_{crit}\)</span>, y una breve interpretación.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dir_unif_test_3D</span>(<span class="dt">dir =</span> direcciones,<span class="dt">dip =</span> inclinaciones,<span class="dt">conf.level =</span> <span class="dv">1</span><span class="op">-</span>a)</code></pre>
<pre><code>## $R
## [1] 0.992
## 
## $Rcrit
## [1] 0.645
## 
## $interpretation
## [1] &quot;Reject H0 and conclude that the sample has a preferred mean direction&quot;</code></pre>
<blockquote>
<p>Conclusión: La muestra presenta una direccional preferencial, <span class="math inline">\(\bar{\theta}=16.13^{\circ}\)</span>, <span class="math inline">\(\bar{R}=.992\)</span>.</p>
</blockquote>
</div>
<div id="prueba-de-tendencia-específica-1" class="section level4">
<h4><span class="header-section-number">17.4.2.2</span> Prueba de tendencia específica</h4>
<p>Esta prueba es similar a la de datos circulares, y es homóloga a la prueba <span class="math inline">\(t\)</span> de una muestra, ya que quiere probar si las mediciones corresponden con una dirección específica. L que se hace es calcular un cono de confianza alrededor de la dirección media de la muestra y ver si la dirección a la cual se quiere comparar cae dentro de este ángulo, similar a usar intervalos de confianza en estadística clásica.</p>
<p>Las hipótesis nula y alterna serían las siguientes:</p>
<ul>
<li><span class="math inline">\(H_0: \bar{\phi} = \phi_0\)</span></li>
<li><span class="math inline">\(H_1: \bar{\phi} \neq \phi_0\)</span></li>
</ul>
<p>El cono de confianza, Ecuación <a href="estadística-direccional.html#eq:cono-conf-esf">(17.20)</a>, está en función del error estándar, Ecuación <a href="estadística-direccional.html#eq:se-esf">(17.19)</a>, que se basa en la resultante y el nivel de significancia deseado. El resultado del error estándar está en <strong>radianes</strong>, por lo que hay que pasarlo a grados.</p>
<p><span class="math display" id="eq:se-esf">\[\begin{equation}
  s_{1-\alpha} = \arccos \left( 1 - \frac{N-R}{R} \left[ \left( \frac{1}{\alpha} \right)^{\frac{1}{N-1}} - 1\right] \right)
  \tag{17.19}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:cono-conf-esf">\[\begin{equation}
  \bar{\phi} \pm s_{1-\alpha}
  \tag{17.20}
\end{equation}\]</span></p>
<p>El cono y cono de confianza se incluye en el resultado de <code>dir_stats_3D</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dir_stats_3D</span>(<span class="dt">dir =</span> direcciones,<span class="dt">dip =</span> inclinaciones,<span class="dt">conf.level =</span> <span class="dv">1</span><span class="op">-</span>a)</code></pre>
<pre><code>## # A tibble: 1 x 8
##   Mean.Dir MeanDip     R Sph.Var Conc.Param Cone.lower Cone.upper  Cone
##      &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;
## 1     16.2    38.7 0.992 0.00821       81.2        9.5       22.8  6.68</code></pre>
<blockquote>
<p>Conclusión: La muestra pudo provenir de una población con dirección <span class="math inline">\(9.5^{\circ} &lt; \bar{\theta} &lt; 22.8^{\circ}\)</span>.</p>
</blockquote>
</div>
<div id="prueba-de-igualdad-entre-dos-muestras-1" class="section level4">
<h4><span class="header-section-number">17.4.2.3</span> Prueba de igualdad entre dos muestras</h4>
<p>Esta prueba es homóloga a la prueba <span class="math inline">\(t\)</span> de dos muestras independientes, y la idea es determinar si dos muestras de mediciones poseen una misma dirección media.</p>
<p>Las hipótesis nula y alterna serían las siguientes:</p>
<ul>
<li><span class="math inline">\(H_0: \bar{\phi}_1 = \bar{\phi}_2\)</span></li>
<li><span class="math inline">\(H_1: \bar{\phi}_1 \neq \bar{\phi}_2\)</span></li>
</ul>
<p>La prueba tiene el supuesto de que la varianza es la misma en las muestras, por lo que es recomendado revisar que se cumpla. La prueba de la igualdad de varianzas se realiza similar a la de igualdad de varianzas en estadística clásica, donde para este caso se analiza la razón entre parámetros de concentración conforme la Ecuación <a href="estadística-direccional.html#eq:k-esf">(17.21)</a>, dada la relación inversa entre varianza esférica y <span class="math inline">\(\kappa\)</span>.</p>
<p><span class="math display" id="eq:k-esf">\[\begin{equation}
  F_{2n_1-2,2n_2-2} = \frac{\kappa_1}{\kappa_2}, \kappa_1 &gt; \kappa_2
  \tag{17.21}
\end{equation}\]</span></p>
<p>La prueba es una prueba <span class="math inline">\(F\)</span> con grados de libertad <span class="math inline">\(2\)</span> y <span class="math inline">\(2[N-2]\)</span>, y se usa la Ecuación <a href="estadística-direccional.html#eq:f-esf">(17.22)</a>.</p>
<p><span class="math display" id="eq:f-esf">\[\begin{equation}
  F_{2,2[N-2]} = \frac{(N-2)(R_1+R_2-R_c)}{N-R_1-R_2}
  \tag{17.22}
\end{equation}\]</span></p>
<p>donde <span class="math inline">\(N\)</span> es el total de observaciones de las dos muestras, <span class="math inline">\(R_1\)</span> es la resultante de la muestra 1, <span class="math inline">\(R_2\)</span> es la resultante de la muestra 2, y <span class="math inline">\(R_c\)</span> es la resultante combinando las dos muestras.</p>
<p>Analizando la igualdad de varianzas se tiene:</p>
<p><span class="math display">\[\begin{equation}
  n_1=6; n_2=6\\
  F_{2n_1-2,2n_2-2} = \frac{\kappa_1}{\kappa_2}\\
  F_{10,10} = \frac{81.2}{2.01} = 40.4\\
  F_{crit} = 2.98
\end{equation}\]</span></p>
<p>Con este análisis se obtiene que las varianzas no son iguales, por lo que técnicamente no sería conveniente realizar la prueba de igualdad de direcciones medias, pero se realiza para efectos demostrativos.</p>
<p>La función <code>dir_2sample_test_3D</code> de <em>GMisc</em> realiza esta prueba, brindando <span class="math inline">\(F\)</span>, <span class="math inline">\(F_{crit}\)</span>, valor-<em>p</em>, y una interpretación.</p>
<pre class="sourceCode r"><code class="sourceCode r">d2 =<span class="st"> </span><span class="kw">c</span>(<span class="fl">111.7</span>,<span class="fl">109.2</span>,<span class="fl">185.1</span>,<span class="fl">83.1</span>,<span class="fl">235.2</span>,<span class="fl">226.7</span>)
i2 =<span class="st"> </span><span class="kw">c</span>(<span class="fl">40.4</span>,<span class="fl">31.4</span>,<span class="fl">25.9</span>,<span class="fl">26.2</span>,<span class="dv">27</span>,<span class="fl">31.5</span>)
<span class="kw">dir_2sample_test_3D</span>(direcciones, inclinaciones, d2, i2, <span class="dt">conf.level =</span> <span class="dv">1</span><span class="op">-</span>a)</code></pre>
<pre><code>## $f
## [1] 12.59
## 
## $fcrit
## [1] 3.49
## 
## $p_value
## [1] 0.000289
## 
## $interpretation
## [1] &quot;Reject H0 and conclude that the two samples could not come from the same population with the same mean direction and mean dip angle&quot;</code></pre>
<blockquote>
<p>Conclusión: Las muestras presentan diferentes varianzas, <span class="math inline">\(F(10,10) = 40.4\)</span>, <span class="math inline">\(p &lt; .001\)</span>, y difieren significativamente en su dirección, <span class="math inline">\(F(2,20) = 12.59\)</span>, <span class="math inline">\(p &lt; .001\)</span></p>
</blockquote>
<p>Otra forma de realizar la prueba sería obtener los conos de confianza para ambas muestras y ver si la dirección media de una cae dentro del cono de la otra.</p>
<p>Lo anterior es más fácil visualizarlo en una red estereográfica. La función <code>stereo_mean</code> de <em>GMisc</em> grafica la dirección media junto con el cono de confianza en la red estereográfica, donde la Figura <a href="estadística-direccional.html#fig:stereo-2-esf">17.6</a> muestra los datos del ejemplo.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">stereo_mean</span>(direcciones,inclinaciones)
<span class="kw">stereo_mean</span>(d2,i2,<span class="dt">mean.col =</span> <span class="st">&#39;blue&#39;</span>,<span class="dt">add =</span> T)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:stereo-2-esf"></span>
<img src="geolonum_files/figure-html/stereo-2-esf-1.png" alt="Red estereográfica mostrando la dirección media y cono de confianza para los datos del ejemplo de dos muestras de datos esféricos. En rojo los datos de la muestra 1 y en azul los datos de la muestra 2." width="100%" />
<p class="caption">
Figura 17.6: Red estereográfica mostrando la dirección media y cono de confianza para los datos del ejemplo de dos muestras de datos esféricos. En rojo los datos de la muestra 1 y en azul los datos de la muestra 2.
</p>
</div>

</div>
</div>
</div>
</div>
<h3>Referencias</h3>
<div id="refs" class="references">
<div id="ref-borradaile2003">
<p>Borradaile, G. J. (2003). <em>Statistics of Earth Science Data: Their Distribution in Time, Space and Orientation</em>. Springer-Verlag Berlin Heidelberg.</p>
</div>
<div id="ref-davis2002">
<p>Davis, J. C. (2002). <em>Statistics and Data Analysis in Geology</em> (3.ª ed.). John Wiley &amp; Sons.</p>
</div>
<div id="ref-fisher1993">
<p>Fisher, N. I., Lewis, T., &amp; Embleton, B. J. J. (1993). <em>Statistical Analysis of Spherical Data</em>. Cambridge University Press.</p>
</div>
<div id="ref-R-GMisc">
<p>Garnier-Villarreal, M. (2020). <em>GMisc: Miscellaneous Functions for Geology (and its areas)</em>. <a href="http://github.com/maxgav13/GMisc">http://github.com/maxgav13/GMisc</a></p>
</div>
<div id="ref-mardia2000">
<p>Mardia, K. V., &amp; Jupp, P. E. (2000). <em>Directional Statistics</em>. John Wiley &amp; Sons.</p>
</div>
<div id="ref-mckillup2010">
<p>McKillup, S., &amp; Darby Dyar, M. (2010). <em>Geostatistics Explained: An Introductory Guide for Earth Scientists</em>. Cambridge University Press. <a href="www.cambridge.org/9780521763226">www.cambridge.org/9780521763226</a></p>
</div>
<div id="ref-swan1995">
<p>Swan, A., &amp; Sandilands, M. (1995). <em>Introduction to Geological Data Analysis</em>. Blackwell Science.</p>
</div>
<div id="ref-trauth2015">
<p>Trauth, M. (2015). <em>MATLAB® Recipes for Earth Sciences</em> (4.ª ed.). Springer-Verlag Berlin Heidelberg.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="estadística-no-paramétrica.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="secuencias-de-datos.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
