<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 9 Estadística Descriptiva Univariable | Geología Numérica: Ciencia de Datos para Geociencias</title>
  <meta name="description" content="Este documento compila el funcionamiento básico del software estadístico y de programación R, así como rutinas y/o comandos específicos para resolver problemas de análisis de datos en geociencias." />
  <meta name="generator" content="bookdown 0.11 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 9 Estadística Descriptiva Univariable | Geología Numérica: Ciencia de Datos para Geociencias" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Este documento compila el funcionamiento básico del software estadístico y de programación R, así como rutinas y/o comandos específicos para resolver problemas de análisis de datos en geociencias." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 9 Estadística Descriptiva Univariable | Geología Numérica: Ciencia de Datos para Geociencias" />
  
  <meta name="twitter:description" content="Este documento compila el funcionamiento básico del software estadístico y de programación R, así como rutinas y/o comandos específicos para resolver problemas de análisis de datos en geociencias." />
  

<meta name="author" content="Maximiliano Garnier Villarreal" />


<meta name="date" content="2020-07-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introducción-a-estadística.html">
<link rel="next" href="estadística-descriptiva-bivariable.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/dygraphs-1.1.1/shapes.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.6/dygraphs.js"></script>
<script src="libs/plotly-binding-4.9.2/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.11/datatables.js"></script>
<link href="libs/dt-core-1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.19/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.19/js/jquery.dataTables.min.js"></script>
<link href="libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet" />
<script src="libs/nouislider-7.0.10/jquery.nouislider.min.js"></script>
<link href="libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet" />
<script src="libs/selectize-0.12.0/selectize.min.js"></script>
<script src="libs/proj4js-2.3.15/proj4.js"></script>
<link href="libs/highcharts-7.0.1/css/motion.css" rel="stylesheet" />
<link href="libs/highcharts-7.0.1/css/htmlwdgtgrid.css" rel="stylesheet" />
<script src="libs/highcharts-7.0.1/highcharts.js"></script>
<script src="libs/highcharts-7.0.1/highcharts-3d.js"></script>
<script src="libs/highcharts-7.0.1/highcharts-more.js"></script>
<script src="libs/highcharts-7.0.1/modules/stock.js"></script>
<script src="libs/highcharts-7.0.1/modules/map.js"></script>
<script src="libs/highcharts-7.0.1/modules/annotations.js"></script>
<script src="libs/highcharts-7.0.1/modules/boost.js"></script>
<script src="libs/highcharts-7.0.1/modules/data.js"></script>
<script src="libs/highcharts-7.0.1/modules/drag-panes.js"></script>
<script src="libs/highcharts-7.0.1/modules/drilldown.js"></script>
<script src="libs/highcharts-7.0.1/modules/item-series.js"></script>
<script src="libs/highcharts-7.0.1/modules/offline-exporting.js"></script>
<script src="libs/highcharts-7.0.1/modules/overlapping-datalabels.js"></script>
<script src="libs/highcharts-7.0.1/modules/exporting.js"></script>
<script src="libs/highcharts-7.0.1/modules/export-data.js"></script>
<script src="libs/highcharts-7.0.1/modules/funnel.js"></script>
<script src="libs/highcharts-7.0.1/modules/heatmap.js"></script>
<script src="libs/highcharts-7.0.1/modules/treemap.js"></script>
<script src="libs/highcharts-7.0.1/modules/sankey.js"></script>
<script src="libs/highcharts-7.0.1/modules/solid-gauge.js"></script>
<script src="libs/highcharts-7.0.1/modules/streamgraph.js"></script>
<script src="libs/highcharts-7.0.1/modules/sunburst.js"></script>
<script src="libs/highcharts-7.0.1/modules/vector.js"></script>
<script src="libs/highcharts-7.0.1/modules/wordcloud.js"></script>
<script src="libs/highcharts-7.0.1/modules/xrange.js"></script>
<script src="libs/highcharts-7.0.1/modules/tilemap.js"></script>
<script src="libs/highcharts-7.0.1/modules/venn.js"></script>
<script src="libs/highcharts-7.0.1/modules/gantt.js"></script>
<script src="libs/highcharts-7.0.1/modules/timeline.js"></script>
<script src="libs/highcharts-7.0.1/modules/parallel-coordinates.js"></script>
<script src="libs/highcharts-7.0.1/plugins/grouped-categories.js"></script>
<script src="libs/highcharts-7.0.1/plugins/motion.js"></script>
<script src="libs/highcharts-7.0.1/plugins/multicolor_series.js"></script>
<script src="libs/highcharts-7.0.1/custom/reset.js"></script>
<script src="libs/highcharts-7.0.1/custom/symbols-extra.js"></script>
<script src="libs/highcharts-7.0.1/custom/text-symbols.js"></script>
<script src="libs/highchart-binding-0.7.0/highchart.js"></script>
<script src="libs/highcharts-regression.js-7.0.1/highcharts-regression.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.2/leaflet.js"></script>
<script src="libs/leaflet-providers-1.1.17/leaflet-providers.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.2/leaflet-providers-plugin.js"></script>
<link href="libs/HomeButton-0.0.1/home-button.css" rel="stylesheet" />
<script src="libs/HomeButton-0.0.1/home-button.js"></script>
<script src="libs/HomeButton-0.0.1/easy-button-src.min.js"></script>
<script src="libs/clipboard-0.0.1/setClipboardText.js"></script>
<link href="libs/PopupTable-0.0.1/popup.css" rel="stylesheet" />
<script src="libs/pacifico-1/data_stars_pacificocdf13b.txt"></script>
<script src="libs/joda-0.0.1/joda.js"></script>
<script src="libs/joda-0.0.1/addImageQuery-bindings.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Geologia Numerica</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefacio</a></li>
<li class="part"><span><b>R</b></span></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a><ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#instalación-de-r-y-rstudio"><i class="fa fa-check"></i><b>1.1</b> Instalación de R y RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#paquetes"><i class="fa fa-check"></i><b>1.2</b> Paquetes</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#ayuda-en-r"><i class="fa fa-check"></i><b>1.3</b> Ayuda en R</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#rmarkdown"><i class="fa fa-check"></i><b>1.4</b> RMarkdown</a><ul>
<li class="chapter" data-level="1.4.1" data-path="intro.html"><a href="intro.html#tipos-de-resultados"><i class="fa fa-check"></i><b>1.4.1</b> Tipos de resultados</a></li>
<li class="chapter" data-level="1.4.2" data-path="intro.html"><a href="intro.html#formulas"><i class="fa fa-check"></i><b>1.4.2</b> Formulas</a></li>
<li class="chapter" data-level="1.4.3" data-path="intro.html"><a href="intro.html#importando-datos"><i class="fa fa-check"></i><b>1.4.3</b> Importando datos</a></li>
<li class="chapter" data-level="1.4.4" data-path="intro.html"><a href="intro.html#cálculos-en-linea"><i class="fa fa-check"></i><b>1.4.4</b> Cálculos en linea</a></li>
<li class="chapter" data-level="1.4.5" data-path="intro.html"><a href="intro.html#importando-figuras"><i class="fa fa-check"></i><b>1.4.5</b> Importando figuras</a></li>
<li class="chapter" data-level="1.4.6" data-path="intro.html"><a href="intro.html#salvando-y-compartiendo"><i class="fa fa-check"></i><b>1.4.6</b> Salvando y compartiendo</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#recursos"><i class="fa fa-check"></i><b>1.5</b> Recursos</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basico.html"><a href="basico.html"><i class="fa fa-check"></i><b>2</b> Funcionamiento básico de R</a><ul>
<li class="chapter" data-level="2.1" data-path="basico.html"><a href="basico.html#introducción"><i class="fa fa-check"></i><b>2.1</b> Introducción</a></li>
<li class="chapter" data-level="2.2" data-path="basico.html"><a href="basico.html#operaciones-básicas"><i class="fa fa-check"></i><b>2.2</b> Operaciones básicas</a></li>
<li class="chapter" data-level="2.3" data-path="basico.html"><a href="basico.html#crear-objetos"><i class="fa fa-check"></i><b>2.3</b> Crear objetos</a></li>
<li class="chapter" data-level="2.4" data-path="basico.html"><a href="basico.html#vectores"><i class="fa fa-check"></i><b>2.4</b> Vectores</a><ul>
<li class="chapter" data-level="2.4.1" data-path="basico.html"><a href="basico.html#numéricos"><i class="fa fa-check"></i><b>2.4.1</b> Numéricos</a></li>
<li class="chapter" data-level="2.4.2" data-path="basico.html"><a href="basico.html#texto-string-character"><i class="fa fa-check"></i><b>2.4.2</b> Texto (string, character)</a></li>
<li class="chapter" data-level="2.4.3" data-path="basico.html"><a href="basico.html#categóricos-factores"><i class="fa fa-check"></i><b>2.4.3</b> Categóricos (factores)</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="basico.html"><a href="basico.html#matrices"><i class="fa fa-check"></i><b>2.5</b> Matrices</a></li>
<li class="chapter" data-level="2.6" data-path="basico.html"><a href="basico.html#dataframes-listas-y-tibbles"><i class="fa fa-check"></i><b>2.6</b> DataFrames, listas y tibbles</a></li>
<li class="chapter" data-level="2.7" data-path="basico.html"><a href="basico.html#verificando-objetos"><i class="fa fa-check"></i><b>2.7</b> Verificando objetos</a></li>
<li class="chapter" data-level="2.8" data-path="basico.html"><a href="basico.html#guardando-el-espacio-de-trabajo"><i class="fa fa-check"></i><b>2.8</b> Guardando el espacio de trabajo</a></li>
<li class="chapter" data-level="2.9" data-path="basico.html"><a href="basico.html#importandocargando-datos"><i class="fa fa-check"></i><b>2.9</b> Importando/cargando datos</a></li>
<li class="chapter" data-level="2.10" data-path="basico.html"><a href="basico.html#exportando-datos"><i class="fa fa-check"></i><b>2.10</b> Exportando datos</a></li>
<li class="chapter" data-level="2.11" data-path="basico.html"><a href="basico.html#inspeccionando-los-datos"><i class="fa fa-check"></i><b>2.11</b> Inspeccionando los datos</a></li>
<li class="chapter" data-level="2.12" data-path="basico.html"><a href="basico.html#descripciones-generales-globales"><i class="fa fa-check"></i><b>2.12</b> Descripciones generales (globales)</a></li>
<li class="chapter" data-level="2.13" data-path="basico.html"><a href="basico.html#recursos-1"><i class="fa fa-check"></i><b>2.13</b> Recursos</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="avanzado.html"><a href="avanzado.html"><i class="fa fa-check"></i><b>3</b> Funcionamiento avanzado de R</a><ul>
<li class="chapter" data-level="3.1" data-path="avanzado.html"><a href="avanzado.html#introducción-1"><i class="fa fa-check"></i><b>3.1</b> Introducción</a></li>
<li class="chapter" data-level="3.2" data-path="avanzado.html"><a href="avanzado.html#operadores-lógicos"><i class="fa fa-check"></i><b>3.2</b> Operadores lógicos</a></li>
<li class="chapter" data-level="3.3" data-path="avanzado.html"><a href="avanzado.html#operador-de-secuencia-pipe-operator"><i class="fa fa-check"></i><b>3.3</b> Operador de secuencia (Pipe operator)</a></li>
<li class="chapter" data-level="3.4" data-path="avanzado.html"><a href="avanzado.html#resumen-de-variables"><i class="fa fa-check"></i><b>3.4</b> Resumen de variables</a></li>
<li class="chapter" data-level="3.5" data-path="avanzado.html"><a href="avanzado.html#selección-y-renombre-de-variables"><i class="fa fa-check"></i><b>3.5</b> Selección y renombre de variables</a><ul>
<li class="chapter" data-level="3.5.1" data-path="avanzado.html"><a href="avanzado.html#select-helpers"><i class="fa fa-check"></i><b>3.5.1</b> <code>select</code> helpers</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="avanzado.html"><a href="avanzado.html#filtrado-de-observaciones"><i class="fa fa-check"></i><b>3.6</b> Filtrado de observaciones</a></li>
<li class="chapter" data-level="3.7" data-path="avanzado.html"><a href="avanzado.html#orden-de-acuerdo-a-variables"><i class="fa fa-check"></i><b>3.7</b> Orden de acuerdo a variables</a></li>
<li class="chapter" data-level="3.8" data-path="avanzado.html"><a href="avanzado.html#creación-de-variables"><i class="fa fa-check"></i><b>3.8</b> Creación de variables</a></li>
<li class="chapter" data-level="3.9" data-path="avanzado.html"><a href="avanzado.html#conteo-de-variables-cualitativas"><i class="fa fa-check"></i><b>3.9</b> Conteo de variables cualitativas</a></li>
<li class="chapter" data-level="3.10" data-path="avanzado.html"><a href="avanzado.html#tabla-interactiva"><i class="fa fa-check"></i><b>3.10</b> Tabla interactiva</a></li>
<li class="chapter" data-level="3.11" data-path="avanzado.html"><a href="avanzado.html#datos-relacionales"><i class="fa fa-check"></i><b>3.11</b> Datos relacionales</a><ul>
<li class="chapter" data-level="3.11.1" data-path="avanzado.html"><a href="avanzado.html#uniones-de-transformación"><i class="fa fa-check"></i><b>3.11.1</b> Uniones de transformación</a></li>
<li class="chapter" data-level="3.11.2" data-path="avanzado.html"><a href="avanzado.html#uniones-de-filtro"><i class="fa fa-check"></i><b>3.11.2</b> Uniones de filtro</a></li>
</ul></li>
<li class="chapter" data-level="3.12" data-path="avanzado.html"><a href="avanzado.html#datos-ordenados-tidy-data"><i class="fa fa-check"></i><b>3.12</b> Datos ordenados (Tidy data)</a><ul>
<li class="chapter" data-level="3.12.1" data-path="avanzado.html"><a href="avanzado.html#formatos-largo-y-ancho"><i class="fa fa-check"></i><b>3.12.1</b> Formatos largo y ancho</a></li>
<li class="chapter" data-level="3.12.2" data-path="avanzado.html"><a href="avanzado.html#separar-y-unir"><i class="fa fa-check"></i><b>3.12.2</b> Separar y unir</a></li>
</ul></li>
<li class="chapter" data-level="3.13" data-path="avanzado.html"><a href="avanzado.html#nest"><i class="fa fa-check"></i><b>3.13</b> Datos anidados (Nesting)</a></li>
<li class="chapter" data-level="3.14" data-path="avanzado.html"><a href="avanzado.html#recursos-2"><i class="fa fa-check"></i><b>3.14</b> Recursos</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="gráficos-1.html"><a href="gráficos-1.html"><i class="fa fa-check"></i><b>4</b> Gráficos</a><ul>
<li class="chapter" data-level="4.1" data-path="gráficos-1.html"><a href="gráficos-1.html#introducción-2"><i class="fa fa-check"></i><b>4.1</b> Introducción</a></li>
<li class="chapter" data-level="4.2" data-path="gráficos-1.html"><a href="gráficos-1.html#estáticos"><i class="fa fa-check"></i><b>4.2</b> Estáticos</a><ul>
<li class="chapter" data-level="4.2.1" data-path="gráficos-1.html"><a href="gráficos-1.html#histograma"><i class="fa fa-check"></i><b>4.2.1</b> Histograma</a></li>
<li class="chapter" data-level="4.2.2" data-path="gráficos-1.html"><a href="gráficos-1.html#barras"><i class="fa fa-check"></i><b>4.2.2</b> Barras</a></li>
<li class="chapter" data-level="4.2.3" data-path="gráficos-1.html"><a href="gráficos-1.html#boxplot"><i class="fa fa-check"></i><b>4.2.3</b> Boxplot</a></li>
<li class="chapter" data-level="4.2.4" data-path="gráficos-1.html"><a href="gráficos-1.html#dispersión"><i class="fa fa-check"></i><b>4.2.4</b> Dispersión</a></li>
<li class="chapter" data-level="4.2.5" data-path="gráficos-1.html"><a href="gráficos-1.html#líneas"><i class="fa fa-check"></i><b>4.2.5</b> líneas</a></li>
<li class="chapter" data-level="4.2.6" data-path="gráficos-1.html"><a href="gráficos-1.html#gráficos-estadísticos"><i class="fa fa-check"></i><b>4.2.6</b> Gráficos estadísticos</a></li>
<li class="chapter" data-level="4.2.7" data-path="gráficos-1.html"><a href="gráficos-1.html#transformación-de-ejes"><i class="fa fa-check"></i><b>4.2.7</b> Transformación de ejes</a></li>
<li class="chapter" data-level="4.2.8" data-path="gráficos-1.html"><a href="gráficos-1.html#limites-de-ejes-zoom"><i class="fa fa-check"></i><b>4.2.8</b> Limites de ejes (Zoom)</a></li>
<li class="chapter" data-level="4.2.9" data-path="gráficos-1.html"><a href="gráficos-1.html#salvando-gráficos"><i class="fa fa-check"></i><b>4.2.9</b> Salvando gráficos</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="gráficos-1.html"><a href="gráficos-1.html#interactivos"><i class="fa fa-check"></i><b>4.3</b> Interactivos</a><ul>
<li class="chapter" data-level="4.3.1" data-path="gráficos-1.html"><a href="gráficos-1.html#histograma-1"><i class="fa fa-check"></i><b>4.3.1</b> Histograma</a></li>
<li class="chapter" data-level="4.3.2" data-path="gráficos-1.html"><a href="gráficos-1.html#barras-1"><i class="fa fa-check"></i><b>4.3.2</b> Barras</a></li>
<li class="chapter" data-level="4.3.3" data-path="gráficos-1.html"><a href="gráficos-1.html#boxplot-1"><i class="fa fa-check"></i><b>4.3.3</b> Boxplot</a></li>
<li class="chapter" data-level="4.3.4" data-path="gráficos-1.html"><a href="gráficos-1.html#dispersión-1"><i class="fa fa-check"></i><b>4.3.4</b> Dispersión</a></li>
<li class="chapter" data-level="4.3.5" data-path="gráficos-1.html"><a href="gráficos-1.html#líneas-1"><i class="fa fa-check"></i><b>4.3.5</b> líneas</a></li>
<li class="chapter" data-level="4.3.6" data-path="gráficos-1.html"><a href="gráficos-1.html#transformación-de-ejes-1"><i class="fa fa-check"></i><b>4.3.6</b> Transformación de ejes</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="gráficos-1.html"><a href="gráficos-1.html#recursos-3"><i class="fa fa-check"></i><b>4.4</b> Recursos</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="iteración.html"><a href="iteración.html"><i class="fa fa-check"></i><b>5</b> Iteración</a><ul>
<li class="chapter" data-level="5.1" data-path="iteración.html"><a href="iteración.html#introducción-3"><i class="fa fa-check"></i><b>5.1</b> Introducción</a></li>
<li class="chapter" data-level="5.2" data-path="iteración.html"><a href="iteración.html#iterando-sobre-un-objeto"><i class="fa fa-check"></i><b>5.2</b> Iterando sobre un objeto</a></li>
<li class="chapter" data-level="5.3" data-path="iteración.html"><a href="iteración.html#iterando-sobre-dos-objetos"><i class="fa fa-check"></i><b>5.3</b> Iterando sobre dos objetos</a></li>
<li class="chapter" data-level="5.4" data-path="iteración.html"><a href="iteración.html#leyendo-archivos-y-combinándolos"><i class="fa fa-check"></i><b>5.4</b> Leyendo archivos y combinándolos</a></li>
<li class="chapter" data-level="5.5" data-path="iteración.html"><a href="iteración.html#datos-anidados-caso-1"><i class="fa fa-check"></i><b>5.5</b> Datos anidados, caso 1</a><ul>
<li class="chapter" data-level="5.5.1" data-path="iteración.html"><a href="iteración.html#efectos-secundarios"><i class="fa fa-check"></i><b>5.5.1</b> Efectos secundarios</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="iteración.html"><a href="iteración.html#datos-anidados-caso-2"><i class="fa fa-check"></i><b>5.6</b> Datos anidados, caso 2</a></li>
<li class="chapter" data-level="5.7" data-path="iteración.html"><a href="iteración.html#recursos-4"><i class="fa fa-check"></i><b>5.7</b> Recursos</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="datos-espaciales.html"><a href="datos-espaciales.html"><i class="fa fa-check"></i><b>6</b> Datos espaciales</a><ul>
<li class="chapter" data-level="6.1" data-path="datos-espaciales.html"><a href="datos-espaciales.html#introducción-4"><i class="fa fa-check"></i><b>6.1</b> Introducción</a></li>
<li class="chapter" data-level="6.2" data-path="datos-espaciales.html"><a href="datos-espaciales.html#paquetes-para-datos-espaciales"><i class="fa fa-check"></i><b>6.2</b> Paquetes para datos espaciales</a></li>
<li class="chapter" data-level="6.3" data-path="datos-espaciales.html"><a href="datos-espaciales.html#sistemas-de-referencias-de-coordenadas-crs"><i class="fa fa-check"></i><b>6.3</b> Sistemas de Referencias de Coordenadas (CRS)</a></li>
<li class="chapter" data-level="6.4" data-path="datos-espaciales.html"><a href="datos-espaciales.html#importar-datos"><i class="fa fa-check"></i><b>6.4</b> Importar datos</a><ul>
<li class="chapter" data-level="6.4.1" data-path="datos-espaciales.html"><a href="datos-espaciales.html#desde-archivos-de-texto"><i class="fa fa-check"></i><b>6.4.1</b> Desde archivos de texto</a></li>
<li class="chapter" data-level="6.4.2" data-path="datos-espaciales.html"><a href="datos-espaciales.html#desde-archivos-espaciales"><i class="fa fa-check"></i><b>6.4.2</b> Desde archivos espaciales</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="datos-espaciales.html"><a href="datos-espaciales.html#exportar-datos"><i class="fa fa-check"></i><b>6.5</b> Exportar datos</a><ul>
<li class="chapter" data-level="6.5.1" data-path="datos-espaciales.html"><a href="datos-espaciales.html#vectoriales"><i class="fa fa-check"></i><b>6.5.1</b> Vectoriales</a></li>
<li class="chapter" data-level="6.5.2" data-path="datos-espaciales.html"><a href="datos-espaciales.html#raster-1"><i class="fa fa-check"></i><b>6.5.2</b> Raster</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="datos-espaciales.html"><a href="datos-espaciales.html#mapas"><i class="fa fa-check"></i><b>6.6</b> Mapas</a><ul>
<li class="chapter" data-level="6.6.1" data-path="datos-espaciales.html"><a href="datos-espaciales.html#estáticos-1"><i class="fa fa-check"></i><b>6.6.1</b> Estáticos</a></li>
<li class="chapter" data-level="6.6.2" data-path="datos-espaciales.html"><a href="datos-espaciales.html#dinámicos"><i class="fa fa-check"></i><b>6.6.2</b> Dinámicos</a></li>
<li class="chapter" data-level="6.6.3" data-path="datos-espaciales.html"><a href="datos-espaciales.html#modelos-de-sombras"><i class="fa fa-check"></i><b>6.6.3</b> Modelos de sombras</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="datos-espaciales.html"><a href="datos-espaciales.html#recursos-5"><i class="fa fa-check"></i><b>6.7</b> Recursos</a></li>
</ul></li>
<li class="part"><span><b>Análisis de datos</b></span></li>
<li class="chapter" data-level="7" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html"><i class="fa fa-check"></i><b>7</b> Álgebra lineal</a><ul>
<li class="chapter" data-level="7.1" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html#introducción-5"><i class="fa fa-check"></i><b>7.1</b> Introducción</a></li>
<li class="chapter" data-level="7.2" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html#tensores"><i class="fa fa-check"></i><b>7.2</b> Tensores</a><ul>
<li class="chapter" data-level="7.2.1" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html#vectores-1"><i class="fa fa-check"></i><b>7.2.1</b> Vectores</a></li>
<li class="chapter" data-level="7.2.2" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html#matrices-1"><i class="fa fa-check"></i><b>7.2.2</b> Matrices</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html#eigenvectors-y-eigenvalues"><i class="fa fa-check"></i><b>7.3</b> Eigenvectors y Eigenvalues</a><ul>
<li class="chapter" data-level="7.3.1" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html#definición"><i class="fa fa-check"></i><b>7.3.1</b> Definición</a></li>
<li class="chapter" data-level="7.3.2" data-path="álgebra-lineal.html"><a href="álgebra-lineal.html#cálculo"><i class="fa fa-check"></i><b>7.3.2</b> Cálculo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html"><i class="fa fa-check"></i><b>8</b> Introducción a estadística</a><ul>
<li class="chapter" data-level="8.1" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#introducción-6"><i class="fa fa-check"></i><b>8.1</b> Introducción</a></li>
<li class="chapter" data-level="8.2" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#tipos"><i class="fa fa-check"></i><b>8.2</b> Tipos</a></li>
<li class="chapter" data-level="8.3" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#modelos"><i class="fa fa-check"></i><b>8.3</b> Modelos</a></li>
<li class="chapter" data-level="8.4" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#nomenclatura"><i class="fa fa-check"></i><b>8.4</b> Nomenclatura</a></li>
<li class="chapter" data-level="8.5" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#variables"><i class="fa fa-check"></i><b>8.5</b> Variables</a><ul>
<li class="chapter" data-level="8.5.1" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#cualitativa"><i class="fa fa-check"></i><b>8.5.1</b> Cualitativa</a></li>
<li class="chapter" data-level="8.5.2" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#cuantitativa"><i class="fa fa-check"></i><b>8.5.2</b> Cuantitativa</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#métodos-de-análisis"><i class="fa fa-check"></i><b>8.6</b> Métodos de análisis</a></li>
<li class="chapter" data-level="8.7" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#muestreo"><i class="fa fa-check"></i><b>8.7</b> Muestreo</a><ul>
<li class="chapter" data-level="8.7.1" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#tipos-1"><i class="fa fa-check"></i><b>8.7.1</b> Tipos</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="introducción-a-estadística.html"><a href="introducción-a-estadística.html#incertidumbre"><i class="fa fa-check"></i><b>8.8</b> Incertidumbre</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html"><i class="fa fa-check"></i><b>9</b> Estadística Descriptiva Univariable</a><ul>
<li class="chapter" data-level="9.1" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#introducción-7"><i class="fa fa-check"></i><b>9.1</b> Introducción</a></li>
<li class="chapter" data-level="9.2" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#tablas-de-frecuencias"><i class="fa fa-check"></i><b>9.2</b> Tablas de frecuencias</a></li>
<li class="chapter" data-level="9.3" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#gráficas"><i class="fa fa-check"></i><b>9.3</b> Gráficas</a></li>
<li class="chapter" data-level="9.4" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#resúmenes-numéricos"><i class="fa fa-check"></i><b>9.4</b> Resúmenes numéricos</a><ul>
<li class="chapter" data-level="9.4.1" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#medidas-de-tendencia-central"><i class="fa fa-check"></i><b>9.4.1</b> Medidas de tendencia central</a></li>
<li class="chapter" data-level="9.4.2" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#medidas-de-dispersión"><i class="fa fa-check"></i><b>9.4.2</b> Medidas de dispersión</a></li>
<li class="chapter" data-level="9.4.3" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#medidas-de-posición"><i class="fa fa-check"></i><b>9.4.3</b> Medidas de posición</a></li>
<li class="chapter" data-level="9.4.4" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#medidas-de-forma"><i class="fa fa-check"></i><b>9.4.4</b> Medidas de forma</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="estadística-descriptiva-univariable.html"><a href="estadística-descriptiva-univariable.html#resumen-general"><i class="fa fa-check"></i><b>9.5</b> Resumen general</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html"><i class="fa fa-check"></i><b>10</b> Estadística Descriptiva Bivariable</a><ul>
<li class="chapter" data-level="10.1" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#introducción-8"><i class="fa fa-check"></i><b>10.1</b> Introducción</a></li>
<li class="chapter" data-level="10.2" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#covarianza"><i class="fa fa-check"></i><b>10.2</b> Covarianza</a></li>
<li class="chapter" data-level="10.3" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#bivar-cor"><i class="fa fa-check"></i><b>10.3</b> Correlación</a></li>
<li class="chapter" data-level="10.4" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#bivar-reg"><i class="fa fa-check"></i><b>10.4</b> Regresión</a><ul>
<li class="chapter" data-level="10.4.1" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#nomenclatura-1"><i class="fa fa-check"></i><b>10.4.1</b> Nomenclatura</a></li>
<li class="chapter" data-level="10.4.2" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#supuestos"><i class="fa fa-check"></i><b>10.4.2</b> Supuestos</a></li>
<li class="chapter" data-level="10.4.3" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#tipos-2"><i class="fa fa-check"></i><b>10.4.3</b> Tipos</a></li>
<li class="chapter" data-level="10.4.4" data-path="estadística-descriptiva-bivariable.html"><a href="estadística-descriptiva-bivariable.html#medidas-de-ajuste-y-error"><i class="fa fa-check"></i><b>10.4.4</b> Medidas de ajuste y error</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="probabilidad.html"><a href="probabilidad.html"><i class="fa fa-check"></i><b>11</b> Probabilidad</a><ul>
<li class="chapter" data-level="11.1" data-path="probabilidad.html"><a href="probabilidad.html#introducción-9"><i class="fa fa-check"></i><b>11.1</b> Introducción</a></li>
<li class="chapter" data-level="11.2" data-path="probabilidad.html"><a href="probabilidad.html#axiomas-y-nomenclatura"><i class="fa fa-check"></i><b>11.2</b> Axiomas y Nomenclatura</a></li>
<li class="chapter" data-level="11.3" data-path="probabilidad.html"><a href="probabilidad.html#reglas-de-probabilidad"><i class="fa fa-check"></i><b>11.3</b> Reglas de probabilidad</a><ul>
<li class="chapter" data-level="11.3.1" data-path="probabilidad.html"><a href="probabilidad.html#regla-de-la-suma"><i class="fa fa-check"></i><b>11.3.1</b> Regla de la suma</a></li>
<li class="chapter" data-level="11.3.2" data-path="probabilidad.html"><a href="probabilidad.html#regla-de-la-multiplicación"><i class="fa fa-check"></i><b>11.3.2</b> Regla de la multiplicación</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="probabilidad.html"><a href="probabilidad.html#variables-aleatorias"><i class="fa fa-check"></i><b>11.4</b> Variables aleatorias</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="distribuciones-de-probabilidad.html"><a href="distribuciones-de-probabilidad.html"><i class="fa fa-check"></i><b>12</b> Distribuciones de Probabilidad</a><ul>
<li class="chapter" data-level="12.1" data-path="distribuciones-de-probabilidad.html"><a href="distribuciones-de-probabilidad.html#introducción-10"><i class="fa fa-check"></i><b>12.1</b> Introducción</a></li>
<li class="chapter" data-level="12.2" data-path="distribuciones-de-probabilidad.html"><a href="distribuciones-de-probabilidad.html#distribución-binomial"><i class="fa fa-check"></i><b>12.2</b> Distribución Binomial</a></li>
<li class="chapter" data-level="12.3" data-path="distribuciones-de-probabilidad.html"><a href="distribuciones-de-probabilidad.html#distribución-de-poisson"><i class="fa fa-check"></i><b>12.3</b> Distribución de Poisson</a></li>
<li class="chapter" data-level="12.4" data-path="distribuciones-de-probabilidad.html"><a href="distribuciones-de-probabilidad.html#distribución-normal-o-gaussiana"><i class="fa fa-check"></i><b>12.4</b> Distribución Normal o Gaussiana</a><ul>
<li class="chapter" data-level="12.4.1" data-path="distribuciones-de-probabilidad.html"><a href="distribuciones-de-probabilidad.html#distribución-normal-estándar-z"><i class="fa fa-check"></i><b>12.4.1</b> Distribución Normal Estándar (Z)</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="distribuciones-de-probabilidad.html"><a href="distribuciones-de-probabilidad.html#distribuciones-de-probabilidad-en-r"><i class="fa fa-check"></i><b>12.5</b> Distribuciones de probabilidad en <strong>R</strong></a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="introducción-a-estadística-inferencial.html"><a href="introducción-a-estadística-inferencial.html"><i class="fa fa-check"></i><b>13</b> Introducción a Estadística Inferencial</a><ul>
<li class="chapter" data-level="13.1" data-path="introducción-a-estadística-inferencial.html"><a href="introducción-a-estadística-inferencial.html#introducción-11"><i class="fa fa-check"></i><b>13.1</b> Introducción</a></li>
<li class="chapter" data-level="13.2" data-path="introducción-a-estadística-inferencial.html"><a href="introducción-a-estadística-inferencial.html#distribuciones-muestrales"><i class="fa fa-check"></i><b>13.2</b> Distribuciones muestrales</a><ul>
<li class="chapter" data-level="13.2.1" data-path="introducción-a-estadística-inferencial.html"><a href="introducción-a-estadística-inferencial.html#infer-x"><i class="fa fa-check"></i><b>13.2.1</b> Media <span class="math inline">\((\bar{x})\)</span></a></li>
<li class="chapter" data-level="13.2.2" data-path="introducción-a-estadística-inferencial.html"><a href="introducción-a-estadística-inferencial.html#infer-x2"><i class="fa fa-check"></i><b>13.2.2</b> Diferencia de medias <span class="math inline">\((\bar{x}_1-\bar{x}_2)\)</span></a></li>
<li class="chapter" data-level="13.2.3" data-path="introducción-a-estadística-inferencial.html"><a href="introducción-a-estadística-inferencial.html#infer-chi"><i class="fa fa-check"></i><b>13.2.3</b> Varianza <span class="math inline">\((s^2)\)</span></a></li>
<li class="chapter" data-level="13.2.4" data-path="introducción-a-estadística-inferencial.html"><a href="introducción-a-estadística-inferencial.html#infer-f"><i class="fa fa-check"></i><b>13.2.4</b> Dos varianzas <span class="math inline">\(\left( \frac{s_1^2}{s_2^2} \right)\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html"><i class="fa fa-check"></i><b>14</b> Estimación e Hipótesis</a><ul>
<li class="chapter" data-level="14.1" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#introducción-12"><i class="fa fa-check"></i><b>14.1</b> Introducción</a></li>
<li class="chapter" data-level="14.2" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#estim"><i class="fa fa-check"></i><b>14.2</b> Estimación</a><ul>
<li class="chapter" data-level="14.2.1" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#media-1"><i class="fa fa-check"></i><b>14.2.1</b> Media</a></li>
<li class="chapter" data-level="14.2.2" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#estim-diff-medias"><i class="fa fa-check"></i><b>14.2.2</b> Diferencia de medias</a></li>
<li class="chapter" data-level="14.2.3" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#estim-ic-chi"><i class="fa fa-check"></i><b>14.2.3</b> Varianza</a></li>
<li class="chapter" data-level="14.2.4" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#estim-ic-f"><i class="fa fa-check"></i><b>14.2.4</b> Dos varianzas</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#hip"><i class="fa fa-check"></i><b>14.3</b> Hipótesis</a><ul>
<li class="chapter" data-level="14.3.1" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#nula-h_0-y-alterna-h_1"><i class="fa fa-check"></i><b>14.3.1</b> Nula (<span class="math inline">\(H_0\)</span>) y Alterna (<span class="math inline">\(H_1\)</span>)</a></li>
<li class="chapter" data-level="14.3.2" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#resultados-y-errores"><i class="fa fa-check"></i><b>14.3.2</b> Resultados y Errores</a></li>
<li class="chapter" data-level="14.3.3" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#estadístico-de-prueba-y-crítico"><i class="fa fa-check"></i><b>14.3.3</b> Estadístico de prueba y crítico</a></li>
<li class="chapter" data-level="14.3.4" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#contrastes-y-valor-p"><i class="fa fa-check"></i><b>14.3.4</b> Contrastes y valor-<em>p</em></a></li>
<li class="chapter" data-level="14.3.5" data-path="estimación-e-hipótesis.html"><a href="estimación-e-hipótesis.html#decisión"><i class="fa fa-check"></i><b>14.3.5</b> Decisión</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html"><i class="fa fa-check"></i><b>15</b> Pruebas Estadísticas</a><ul>
<li class="chapter" data-level="15.1" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#introducción-13"><i class="fa fa-check"></i><b>15.1</b> Introducción</a></li>
<li class="chapter" data-level="15.2" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#pruebas-param"><i class="fa fa-check"></i><b>15.2</b> Pruebas paramétricas</a><ul>
<li class="chapter" data-level="15.2.1" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#supuestos-pasos"><i class="fa fa-check"></i><b>15.2.1</b> Supuestos y Pasos</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#ES-p"><i class="fa fa-check"></i><b>15.3</b> Tamaño del Efecto</a><ul>
<li class="chapter" data-level="15.3.1" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#familias-de-tamaño-del-efecto"><i class="fa fa-check"></i><b>15.3.1</b> Familias de tamaño del efecto</a></li>
<li class="chapter" data-level="15.3.2" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#ecuaciones-para-tamaños-de-efecto"><i class="fa fa-check"></i><b>15.3.2</b> Ecuaciones para tamaños de efecto</a></li>
<li class="chapter" data-level="15.3.3" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#clasificación-de-tamaños-de-efecto"><i class="fa fa-check"></i><b>15.3.3</b> Clasificación de tamaños de efecto</a></li>
<li class="chapter" data-level="15.3.4" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#importancia-del-tamaño-del-efecto"><i class="fa fa-check"></i><b>15.3.4</b> Importancia del tamaño del efecto</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-z1"><i class="fa fa-check"></i><b>15.4</b> <span class="math inline">\(z\)</span> de 1 muestra</a></li>
<li class="chapter" data-level="15.5" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-t1"><i class="fa fa-check"></i><b>15.5</b> <span class="math inline">\(t\)</span> de 1 muestra</a></li>
<li class="chapter" data-level="15.6" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-t2-ind"><i class="fa fa-check"></i><b>15.6</b> <span class="math inline">\(t\)</span> de 2 muestras independientes</a></li>
<li class="chapter" data-level="15.7" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-t2-dep"><i class="fa fa-check"></i><b>15.7</b> <span class="math inline">\(t\)</span> de 2 muestras dependientes</a></li>
<li class="chapter" data-level="15.8" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-aov"><i class="fa fa-check"></i><b>15.8</b> ANOVA de 1-factor entre-sujetos</a><ul>
<li class="chapter" data-level="15.8.1" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#relación-entre-la-prueba-t-de-2-muestras-independientes-y-anova-de-1-factor-entre-sujetos"><i class="fa fa-check"></i><b>15.8.1</b> Relación entre la prueba <span class="math inline">\(t\)</span> de 2 muestras independientes y ANOVA de 1-factor entre-sujetos</a></li>
</ul></li>
<li class="chapter" data-level="15.9" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-pearson"><i class="fa fa-check"></i><b>15.9</b> Correlación de Pearson</a></li>
<li class="chapter" data-level="15.10" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-rpb"><i class="fa fa-check"></i><b>15.10</b> Correlación Punto Biserial</a></li>
<li class="chapter" data-level="15.11" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-chi"><i class="fa fa-check"></i><b>15.11</b> <span class="math inline">\(\chi^2\)</span> para 1 varianza</a></li>
<li class="chapter" data-level="15.12" data-path="pruebas-estadísticas.html"><a href="pruebas-estadísticas.html#prueba-f"><i class="fa fa-check"></i><b>15.12</b> <span class="math inline">\(F\)</span> para 2 varianzas</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html"><i class="fa fa-check"></i><b>16</b> Estadística No Paramétrica</a><ul>
<li class="chapter" data-level="16.1" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#introducción-14"><i class="fa fa-check"></i><b>16.1</b> Introducción</a></li>
<li class="chapter" data-level="16.2" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#pruebas-noparam"><i class="fa fa-check"></i><b>16.2</b> Pruebas no-paramétricas</a></li>
<li class="chapter" data-level="16.3" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#ES-np"><i class="fa fa-check"></i><b>16.3</b> Tamaño del efecto</a></li>
<li class="chapter" data-level="16.4" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#pruebas-chi2-nominales"><i class="fa fa-check"></i><b>16.4</b> Pruebas <span class="math inline">\(\chi^2\)</span> (nominales)</a><ul>
<li class="chapter" data-level="16.4.1" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#prueba-chi-gof"><i class="fa fa-check"></i><b>16.4.1</b> Bondad de ajuste</a></li>
<li class="chapter" data-level="16.4.2" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#tab-contingencia"><i class="fa fa-check"></i><b>16.4.2</b> Tablas de Contingencia</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#pruebas-sobre-rangos-ordinales"><i class="fa fa-check"></i><b>16.5</b> Pruebas sobre rangos (ordinales)</a><ul>
<li class="chapter" data-level="16.5.1" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#prueba-wilcoxon"><i class="fa fa-check"></i><b>16.5.1</b> Rango con signo de Wilcoxon</a></li>
<li class="chapter" data-level="16.5.2" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#prueba-mwu"><i class="fa fa-check"></i><b>16.5.2</b> Suma de rangos de Wilcoxon / U de Mann-Whitney</a></li>
<li class="chapter" data-level="16.5.3" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#prueba-kruskal"><i class="fa fa-check"></i><b>16.5.3</b> Kruskal-Wallis</a></li>
<li class="chapter" data-level="16.5.4" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#prueba-spearman"><i class="fa fa-check"></i><b>16.5.4</b> Correlación de Spearman</a></li>
</ul></li>
<li class="chapter" data-level="16.6" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#bootstrap"><i class="fa fa-check"></i><b>16.6</b> Bootstrap (remuestreo)</a><ul>
<li class="chapter" data-level="16.6.1" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#infer"><i class="fa fa-check"></i><b>16.6.1</b> <em>infer</em></a></li>
<li class="chapter" data-level="16.6.2" data-path="estadística-no-paramétrica.html"><a href="estadística-no-paramétrica.html#rsample"><i class="fa fa-check"></i><b>16.6.2</b> <em>rsample</em></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="estadística-direccional.html"><a href="estadística-direccional.html"><i class="fa fa-check"></i><b>17</b> Estadística Direccional</a><ul>
<li class="chapter" data-level="17.1" data-path="estadística-direccional.html"><a href="estadística-direccional.html#introducción-15"><i class="fa fa-check"></i><b>17.1</b> Introducción</a></li>
<li class="chapter" data-level="17.2" data-path="estadística-direccional.html"><a href="estadística-direccional.html#representación-gráfica"><i class="fa fa-check"></i><b>17.2</b> Representación gráfica</a></li>
<li class="chapter" data-level="17.3" data-path="estadística-direccional.html"><a href="estadística-direccional.html#datos-circulares"><i class="fa fa-check"></i><b>17.3</b> Datos circulares</a><ul>
<li class="chapter" data-level="17.3.1" data-path="estadística-direccional.html"><a href="estadística-direccional.html#estadística-descriptiva"><i class="fa fa-check"></i><b>17.3.1</b> Estadística descriptiva</a></li>
<li class="chapter" data-level="17.3.2" data-path="estadística-direccional.html"><a href="estadística-direccional.html#estadística-inferencial"><i class="fa fa-check"></i><b>17.3.2</b> Estadística inferencial</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="estadística-direccional.html"><a href="estadística-direccional.html#datos-esféricos"><i class="fa fa-check"></i><b>17.4</b> Datos esféricos</a><ul>
<li class="chapter" data-level="17.4.1" data-path="estadística-direccional.html"><a href="estadística-direccional.html#estadística-descriptiva-1"><i class="fa fa-check"></i><b>17.4.1</b> Estadística descriptiva</a></li>
<li class="chapter" data-level="17.4.2" data-path="estadística-direccional.html"><a href="estadística-direccional.html#estadística-inferencial-1"><i class="fa fa-check"></i><b>17.4.2</b> Estadística inferencial</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="secuencias-de-datos.html"><a href="secuencias-de-datos.html"><i class="fa fa-check"></i><b>18</b> Secuencias de Datos</a></li>
<li class="chapter" data-level="19" data-path="geoestadística.html"><a href="geoestadística.html"><i class="fa fa-check"></i><b>19</b> Geoestadística</a></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Creado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Geología Numérica: Ciencia de Datos para Geociencias</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estadística-descriptiva-univariable" class="section level1">
<h1><span class="header-section-number">Capítulo 9</span> Estadística Descriptiva Univariable</h1>
<div id="introducción-7" class="section level2">
<h2><span class="header-section-number">9.1</span> Introducción</h2>
<p>Como se mencionó en la introducción, la estadística univariable se enfoca en describir una variable a la vez, sin considerar la relación con cualquier otra variable. La descripción y métodos a usar va a estar en función del tipo de variable: cualitativa o cuantitativa. Las tres formas en que se pueden describir los datos son: <em>tabularmente</em> (datos cualitativos o cuantitativos discretos), <em>gráficamente</em>, y por medio de <em>resúmenes numéricos</em>.</p>
</div>
<div id="tablas-de-frecuencias" class="section level2">
<h2><span class="header-section-number">9.2</span> Tablas de frecuencias</h2>
<p>La idea es presentar un resumen de los datos, por lo general por medio de conteos de observaciones por clases. Con datos cualitativos simplemente se cuenta la cantidad de observaciones en cada clase, para datos cuantitativos discretos se cuenta la cantidad de observaciones para cada valor único observado, y para datos cuantitativos continuos lo común es dividir el rango de los valores en una cierta cantidad de clases y contar las observaciones que caen en cada clase.</p>
<p>Las tablas pueden contener diferentes tipos de frecuencias:</p>
<ul>
<li>Absoluta: Conteo de elementos por clase (<span class="math inline">\(n\)</span>)</li>
<li>Relativa: Porcentaje de elementos por clase</li>
<li>Absoluta acumulada: Conteo de elementos que toman un valor menor o igual a una clase, suma a la cantidad de observaciones (<span class="math inline">\(N\)</span>)</li>
<li>Relativa acumulada: Porcentaje de elementos que toman un valor menor o igual a una clase, suma a 1 o <span class="math inline">\(100\%\)</span></li>
</ul>
<p>Para datos cualitativos hay diferentes formas de generar tablas de frecuencias, y dependiendo de lo que se quiera mostrar. Lo más fácil es usar <code>tabyl</code> del paquete <em>janitor</em> y formatearla (Tabla <a href="estadística-descriptiva-univariable.html#tab:tab-cual">9.1</a>). Se va a ejemplificar con los datos <code>gss_cat</code> y la variable <code>marital</code> que vienen con el paquete <em>forcats</em>. Por defecto cuando se usa solo una variable realiza el conteo y calcula el porcentaje de cada categoría. En el ejemplo se redondea a 3 dígitos y se ordena de forma descendente de acuerdo al conteo.</p>
<pre class="sourceCode r"><code class="sourceCode r">gss_cat <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">tabyl</span>(marital) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">adorn_rounding</span>(<span class="dv">3</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="op">-</span>n)</code></pre>
<table>
<caption><span id="tab:tab-cual">Tabla 9.1: </span>Tabla de frecuencias para una variable cualitativa</caption>
<thead>
<tr class="header">
<th align="left">marital</th>
<th align="right">n</th>
<th align="right">percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Married</td>
<td align="right">10117</td>
<td align="right">0.471</td>
</tr>
<tr class="even">
<td align="left">Never married</td>
<td align="right">5416</td>
<td align="right">0.252</td>
</tr>
<tr class="odd">
<td align="left">Divorced</td>
<td align="right">3383</td>
<td align="right">0.157</td>
</tr>
<tr class="even">
<td align="left">Widowed</td>
<td align="right">1807</td>
<td align="right">0.084</td>
</tr>
<tr class="odd">
<td align="left">Separated</td>
<td align="right">743</td>
<td align="right">0.035</td>
</tr>
<tr class="even">
<td align="left">No answer</td>
<td align="right">17</td>
<td align="right">0.001</td>
</tr>
</tbody>
</table>
<p>En el caso de datos cuantitativos continuos, donde hay que dividir el rango de valores en cierta cantidad de clases, no hay una manera única o definida de escoger el número de clases, pero hay algunas sugerencias. Una de las sugerencias se muestra en la Ecuación <a href="estadística-descriptiva-univariable.html#eq:clases-eq">(9.1)</a>.</p>
<p><span class="math display" id="eq:clases-eq">\[\begin{equation}
  k = 1 + 3.33 log_{10}(N)
  \tag{9.1}
\end{equation}\]</span></p>
<p>donde <span class="math inline">\(k\)</span> es el número de clases y <span class="math inline">\(N\)</span> es el total de observaciones (datos). Otra sugerencia se muestra en la Tabla <a href="estadística-descriptiva-univariable.html#tab:clases-tab">9.2</a></p>
<table>
<caption><span id="tab:clases-tab">Tabla 9.2: </span>Sugerencia para el número de clases de acuerdo a la cantidad de observaciones</caption>
<thead>
<tr class="header">
<th align="center">N</th>
<th align="center">k</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">&lt; 50</td>
<td align="center">5 - 7</td>
</tr>
<tr class="even">
<td align="center">50 - 100</td>
<td align="center">6 - 10</td>
</tr>
<tr class="odd">
<td align="center">100 - 250</td>
<td align="center">7 - 12</td>
</tr>
<tr class="even">
<td align="center">&gt; 250</td>
<td align="center">10 - 20</td>
</tr>
</tbody>
</table>
<p>Un ejemplo de una tabla de frecuencia se muestra a continuación en la Tabla <a href="estadística-descriptiva-univariable.html#tab:freq">9.3</a>, usando los datos: 3.1 4.5 2.9 2.7 3.8 5.1 4.9 3.5 2.1 4.2 2.2 1.8 2.5 3.6 3.6 4.3 5.1 6.1 5.7 2.8 2.8 3.7 3.5 4.4 2.5 5.6 5.1 4.7 4.9 4.2 3.6 4.1 4.1 3.7 2.9 6.2 4.8 3.9 4.6 3.1.</p>
<table>
<caption><span id="tab:freq">Tabla 9.3: </span>Tabla de frecuencias para una variable continua</caption>
<thead>
<tr class="header">
<th align="left">Clase</th>
<th align="right">Frecuencia absoluta</th>
<th align="right">Frecuencias relativa</th>
<th align="right">Frec. Abs. Acumulada</th>
<th align="right">Frec. Rel. Acumulada</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1-2</td>
<td align="right">1</td>
<td align="right">0.025</td>
<td align="right">1</td>
<td align="right">0.025</td>
</tr>
<tr class="even">
<td align="left">2-3</td>
<td align="right">9</td>
<td align="right">0.225</td>
<td align="right">10</td>
<td align="right">0.250</td>
</tr>
<tr class="odd">
<td align="left">3-4</td>
<td align="right">11</td>
<td align="right">0.275</td>
<td align="right">21</td>
<td align="right">0.525</td>
</tr>
<tr class="even">
<td align="left">4-5</td>
<td align="right">12</td>
<td align="right">0.300</td>
<td align="right">33</td>
<td align="right">0.825</td>
</tr>
<tr class="odd">
<td align="left">5-6</td>
<td align="right">5</td>
<td align="right">0.125</td>
<td align="right">38</td>
<td align="right">0.950</td>
</tr>
<tr class="even">
<td align="left">6-7</td>
<td align="right">2</td>
<td align="right">0.050</td>
<td align="right">40</td>
<td align="right">1.000</td>
</tr>
</tbody>
</table>
<p>El código para generar la tabla fue el siguiente, donde <code>x</code> corresponde con el vector de datos, <code>breaks</code> con las divisiones para las clases, y <code>labels</code> con los nombres de la clases:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">Freq</span>(x, <span class="dt">breaks =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">7</span>, 
     <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&#39;1-2&#39;</span>,<span class="st">&#39;2-3&#39;</span>,<span class="st">&#39;3-4&#39;</span>,<span class="st">&#39;4-5&#39;</span>,<span class="st">&#39;5-6&#39;</span>,<span class="st">&#39;6-7&#39;</span>))</code></pre>
</div>
<div id="gráficas" class="section level2">
<h2><span class="header-section-number">9.3</span> Gráficas</h2>
<p>Dependiendo del tipo de variable así será la representación gráfica. Para datos cualitativos y cuantitativos discretos lo típico es usar gráficos de barras, mientras que para datos cuantitativos continuos se usa el histograma o gráfico de caja.</p>
<p>El gráfico de barras correspondiente a los datos de la Tabla <a href="estadística-descriptiva-univariable.html#tab:tab-cual">9.1</a> se muestra en la Figura <a href="estadística-descriptiva-univariable.html#fig:barras">9.1</a>. Para refrescar cómo se pueden construir estos gráficos ir a <a href="gráficos-1.html#gráficos-1">Gráficos</a>. La finalidad de esto gráficos es brindar una idea del balance entre las categorías o niveles de una clase y ver si hay alguna categoría o nivel que sobre salga tanto por valores altos como por valores bajos.</p>
<div class="figure" style="text-align: center"><span id="fig:barras"></span>
<img src="geolonum_files/figure-html/barras-1.png" alt="Gráfico de barras para una variable cualitativa" width="70%" />
<p class="caption">
Figura 9.1: Gráfico de barras para una variable cualitativa
</p>
</div>
<p>El histograma (Figura <a href="estadística-descriptiva-univariable.html#fig:hist">9.2</a>) permite dar una primera mirada al tipo de distribución de los datos:</p>
<ul>
<li>Si las alturas de las barras son similares se dice que tiene distribución tipo “uniforme”.</li>
<li>Si las alturas son mayores en la zona central se dice que tiene forma tipo “campana” (distribución normal) y puede ser simétrica o asimétrica, con sesgo hacia el lado positivo o al lado negativo.</li>
<li>Si hay barras muy alejadas del grupo, se dice que son datos atípicos.</li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:hist"></span>
<img src="images/histogramas.png" alt="Ejemplos de histogramas. Tomado de: http://pro.arcgis.com/en/pro-app/tool-reference/spatial-statistics/" width="70%" />
<p class="caption">
Figura 9.2: Ejemplos de histogramas. Tomado de: <a href="http://pro.arcgis.com/en/pro-app/tool-reference/spatial-statistics/" class="uri">http://pro.arcgis.com/en/pro-app/tool-reference/spatial-statistics/</a>
</p>
</div>
<p>El gráfico de caja (Figura <a href="estadística-descriptiva-univariable.html#fig:boxplot">9.3</a>) también puede brindar una idea de la distribución de los datos. Recordar que este tipo de gráfico se compone de los cuartiles <span class="math inline">\(Q_1\)</span> (límite inferior de la caja), <span class="math inline">\(Q_2\)</span> o mediana (barra dentro de la caja), y <span class="math inline">\(Q_3\)</span> (límite superior de la caja). Si los datos presentan una distribución normal tipo campana la mediana aparecería cerca del centro de la caja. Si los datos presentan una asimetría la mediana va a estar más cerca de uno de los bordes, y van a observarse puntos al extremo opuesto de la mediana, los cuales podrían representar valores extremos o atípicos.</p>
<div class="figure" style="text-align: center"><span id="fig:boxplot"></span>
<img src="geolonum_files/figure-html/boxplot-1.png" alt="Gráficos de caja, donde las cruces representan la media. **A** mostrando datos con distribución normal donde la mediana está cerca del medio de la caja. **B** mostrando datos asimétricos donde la mediana está más cerca de uno de los extremos y además se presentan posibles valores atípisoc (puntos)." width="70%" />
<p class="caption">
Figura 9.3: Gráficos de caja, donde las cruces representan la media. <strong>A</strong> mostrando datos con distribución normal donde la mediana está cerca del medio de la caja. <strong>B</strong> mostrando datos asimétricos donde la mediana está más cerca de uno de los extremos y además se presentan posibles valores atípisoc (puntos).
</p>
</div>
<p>Siguiendo con los datos del ejemplo de la Tabla <a href="estadística-descriptiva-univariable.html#tab:freq">9.3</a>, se pueden generar los histogramas (Figura <a href="estadística-descriptiva-univariable.html#fig:histogramas">9.4</a>) correspondientes a las columnas. Para refrescar cómo se pueden construir estos gráficos ir a <a href="gráficos-1.html#gráficos-1">Gráficos</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:histogramas"></span>
<img src="geolonum_files/figure-html/histogramas-1.png" alt="Histogramas de los datos de ejemplo. **A** Frecuencia absoluta, **B** Frecuencia relativa, **C** Frecuencia absoluta acumulada, **D** Frecuencia relativa acumulada." width="90%" />
<p class="caption">
Figura 9.4: Histogramas de los datos de ejemplo. <strong>A</strong> Frecuencia absoluta, <strong>B</strong> Frecuencia relativa, <strong>C</strong> Frecuencia absoluta acumulada, <strong>D</strong> Frecuencia relativa acumulada.
</p>
</div>
</div>
<div id="resúmenes-numéricos" class="section level2">
<h2><span class="header-section-number">9.4</span> Resúmenes numéricos</h2>
<p>Dependiendo del dato que se quiera presentar, éstos se pueden dividir en diferentes tipos. En esta sección se muestran y explican estos diferentes tipos, así como las funciones para calcularlas, enfocándose más en datos cuantitativos continuos.</p>
<div id="medidas-de-tendencia-central" class="section level3">
<h3><span class="header-section-number">9.4.1</span> Medidas de tendencia central</h3>
<p>Esta estadística es la más conocida, ya que representa el centro de la distribución de los datos, siendo la más conocida y usada la media aritmética o promedio (<span class="math inline">\(\bar{x}\)</span>). Además de la media, otras medidas de tendencia central son la media ponderada, media geométrica (<span class="math inline">\(\bar{x}_g\)</span>), mediana, y moda.</p>
<div id="media" class="section level4">
<h4><span class="header-section-number">9.4.1.1</span> Media</h4>
<p>La media aritmética o promedio se muestra en la Ecuación <a href="estadística-descriptiva-univariable.html#eq:media">(9.2)</a> y tiene la característica de ser sensible a valores extremos (atípicos), por lo que no es muy recomendable para distribuciones asimétricas.</p>
<p><span class="math display" id="eq:media">\[\begin{equation}
  \bar{x} = \frac{\sum_{i=1}^{N}{x_i}}{N}
  \tag{9.2}
\end{equation}\]</span></p>
<p>La media ponderada (Ecuación <a href="estadística-descriptiva-univariable.html#eq:media-ponderada">(9.3)</a>) se usa cuando los elementos del vector tienen diferentes pesos (<span class="math inline">\(f\)</span>). La media aritmética es de hecho una simplificación de la media ponderada donde todos los elementos tienen el mismo peso.</p>
<p><span class="math display" id="eq:media-ponderada">\[\begin{equation}
  \bar{x} = \frac{\sum_{i=1}^{k}{f_i m_i}}{\sum f}
  \tag{9.3}
\end{equation}\]</span></p>
</div>
<div id="media-geométrica" class="section level4">
<h4><span class="header-section-number">9.4.1.2</span> Media geométrica</h4>
<p>La media geométrica (Ecuación <a href="estadística-descriptiva-univariable.html#eq:media-geom">(9.4)</a>) es típicamente usada para distribuciones con asimetría positiva (hacia la derecha), y es menos sensible a valores extremos (atípicos). Tiene la condición de que únicamente aplica para valores positivos, no pueden ser cero ni negativos.</p>
<p><span class="math display" id="eq:media-geom">\[\begin{equation}
  \bar{x}_g = \left(x_1 * x_2 * \cdots * x_N \right)^\frac{1}{N}
  \tag{9.4}
\end{equation}\]</span></p>
<p>Los anteriores conceptos se muestran con un ejemplo donde se tiene las notas de exámenes (70, 50, 80, 95) y cada examen tiene diferente peso (20, 20, 20, 40). La media sería <span class="math inline">\(\bar{x} = \frac{70+50+80+95}{4} = 73.75\)</span>, la media ponderada sería <span class="math inline">\(\bar{x} = \frac{70*20+50*20+80*20+95*40}{4} = 78\)</span>, y la media geométrica sería <span class="math inline">\(\bar{x}_g = \left(70 * 50 * 80 * 95 \right)^\frac{1}{4} = 71.81\)</span>.</p>
<p>En <strong>R</strong> se realizaría de la siguiente manera:</p>
<pre class="sourceCode r"><code class="sourceCode r">notas =<span class="st"> </span><span class="kw">c</span>(<span class="dv">70</span>, <span class="dv">50</span>, <span class="dv">80</span>, <span class="dv">95</span>)
pesos =<span class="st"> </span><span class="kw">c</span>(<span class="dv">20</span>, <span class="dv">20</span>, <span class="dv">20</span>, <span class="dv">40</span>)

<span class="kw">mean</span>(notas)</code></pre>
<pre><code>## [1] 73.75</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">weighted.mean</span>(notas, pesos)</code></pre>
<pre><code>## [1] 78</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">Gmean</span>(notas)</code></pre>
<pre><code>## [1] 71.81587</code></pre>
</div>
<div id="mediana" class="section level4">
<h4><span class="header-section-number">9.4.1.3</span> Mediana</h4>
<p>La mediana (Ecuación <a href="estadística-descriptiva-univariable.html#eq:mediana">(9.5)</a>) es el valor de los datos que los divide en dos partes iguales. No se ve afectada por valores extremos, lo que la hace una medida robusta para distribuciones asimétricas.</p>
<p><span class="math display" id="eq:mediana">\[\begin{equation}
  \text{si N es impar} \rightarrow Me = X_\frac{N+1}{2}\\
  \text{si N es par} \rightarrow Me = 0.5 \left(X_\frac{N}{2} + X_\frac{N+1}{2} \right)\\
  \tag{9.5}
\end{equation}\]</span></p>
<p>Ejemplos de la mediana y cómo no se ve afectada por valores extremos serían:</p>
<ul>
<li><span class="math inline">\(1, 2, 4, 5, 6, 6, 8 \rightarrow Me = 5\)</span></li>
<li><span class="math inline">\(1, 2, 4, 5, 6, 6, 6, 8 \rightarrow Me = (5+6)/2 = 5.5\)</span></li>
<li><span class="math inline">\(1, 2, 4, 5, 6, 6, 80 \rightarrow Me = 5\)</span></li>
</ul>
</div>
<div id="moda" class="section level4">
<h4><span class="header-section-number">9.4.1.4</span> Moda</h4>
<p>La moda es el valor más frecuente o que se repite más, es más utilizada para datos discretos, aunque para datos continuos se puede calcular la curva de densidad de los datos y encontrar el pico de dicha curva. También existe la posibilidad de que los datos presenten más de una moda (Figura <a href="estadística-descriptiva-univariable.html#fig:moda">9.5</a>).</p>

<div class="figure" style="text-align: center"><span id="fig:moda"></span>
<img src="images/moda.png" alt="Distribuciones de datos con más de una moda (Trauth, 2015)." width="70%" />
<p class="caption">
Figura 9.5: Distribuciones de datos con más de una moda <span class="citation">(Trauth, <a href="#ref-trauth2015">2015</a>)</span>.
</p>
</div>
<p>En variables con distribución simétrica los valores de media, mediana y moda coinciden. En las distribuciones asimétricas se van distanciando conforme incrementa la asimetría (Figura <a href="estadística-descriptiva-univariable.html#fig:tend-cent">9.6</a>).</p>

<div class="figure" style="text-align: center"><span id="fig:tend-cent"></span>
<img src="images/tend_cent.png" alt="Diferencias entre medidas de tendencia central conforme la distribución presenta mayor asimetría (Trauth, 2015)." width="70%" />
<p class="caption">
Figura 9.6: Diferencias entre medidas de tendencia central conforme la distribución presenta mayor asimetría <span class="citation">(Trauth, <a href="#ref-trauth2015">2015</a>)</span>.
</p>
</div>
</div>
</div>
<div id="medidas-de-dispersión" class="section level3">
<h3><span class="header-section-number">9.4.2</span> Medidas de dispersión</h3>
<p>Estas medidas brindan una idea de la dispersión o variabilidad que presentan los datos con respecto a una medida de tendencia central, típicamente la media. Siempre son positivas e idealmente para reducir la incertidumbre se busca que estas medidas sean lo más pequeñas posibles.</p>
<div id="rango-r" class="section level4">
<h4><span class="header-section-number">9.4.2.1</span> Rango (<span class="math inline">\(R\)</span>)</h4>
<p>El rango toma en cuenta el valor mínimos y máximo de la variable, sin tomar en cuenta el resto de valores intermedios. Se puede expresar de dos maneras: como un vector indicando los valores máximo y mínimo, o como la diferencia entre estos valores (Ecuación <a href="estadística-descriptiva-univariable.html#eq:rango">(9.6)</a>). Una desventaja de presentarlo como al diferencia es que se pierde el contexto de la escala de los datos, ya que una misma diferencia puede estar presente a diferentes escalas. Ejemplo: Los datos pueden tener un rango de 5, pero los datos pueden estar entre 100 y 95 o 25 y 20. Para ambos casos aunque el rango es el mismo no confiere la misma información; en el primer caso la dispersión se puede considerar menor ya que representa un 5% con respecto al valor máximo, mientras que en el segundo caso representa un 20%.</p>
<p><span class="math display" id="eq:rango">\[\begin{equation}
  (a) R = (x_{min},x_{max})\\
  (b) R = x_{max}-x_{min}\\
  \tag{9.6}
\end{equation}\]</span></p>
<p>Una ventaja de esta medida es la facilidad de calcularla e interpretarla, mientras que la desventaja es que considera únicamente los datos extremos y no la totalidad de los mismos, por lo que pudiera verse afectada por valores atípicos.</p>
<p>Usando los datos 2, 6, 11, 8, 11, 4, 7, 5 como ejemplo se puede determinar que <span class="math inline">\(R=(2,11)=9\)</span>. En <strong>R</strong> la función <code>range</code> calcula el rango dando los valores mínimo y máximo, si se quiere la diferencia se puede usar <code>diff</code>, donde toma el segundo elemento y le resta el primero.</p>
<pre class="sourceCode r"><code class="sourceCode r">vec =<span class="st"> </span><span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">6</span>, <span class="dv">11</span>, <span class="dv">8</span>, <span class="dv">11</span>, <span class="dv">4</span>, <span class="dv">7</span>, <span class="dv">5</span>)
<span class="kw">range</span>(vec)</code></pre>
<pre><code>## [1]  2 11</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">diff</span>(<span class="kw">range</span>(vec))</code></pre>
<pre><code>## [1] 9</code></pre>
</div>
<div id="varianza-s2" class="section level4">
<h4><span class="header-section-number">9.4.2.2</span> Varianza (<span class="math inline">\(s^2\)</span>)</h4>
<p>La varianza toma en cuenta todos los datos y su diferencia al cuadrado con respecto a la media, esto se puede visualizar en la Figura <a href="estadística-descriptiva-univariable.html#fig:varianza">9.7</a>, donde la línea vertical roja representa la media, los puntos azules los datos, y las lineas horizontales azules las diferencias cuadradas entre la media y los datos. Una desventaja es que al elevar las diferencias al cuadrado la medida <strong>NO</strong> se encuentra en las mismas unidades (escala) de la variable original.</p>
<div class="figure" style="text-align: center"><span id="fig:varianza"></span>
<img src="images/varianza.png" alt="Representación de la varianza" width="70%" />
<p class="caption">
Figura 9.7: Representación de la varianza
</p>
</div>
<p>La varianza se calcula mediante la Ecuación <a href="estadística-descriptiva-univariable.html#eq:varianza">(9.7)</a>:</p>
<p><span class="math display" id="eq:varianza">\[\begin{equation}
  s^2 = \frac{\sum_{i=1}^{N}{\left(x_i - \bar{x}\right)^2}}{N-1}\\
  \sigma^2 = \frac{\sum_{i=1}^{N}{\left(x_i - \mu\right)}}{N}
  \tag{9.7}
\end{equation}\]</span></p>
<p>En la ecuación anterior <span class="math inline">\(s^2\)</span> es la varianza muestral, <span class="math inline">\(\sigma^2\)</span> la varianza poblacional, <span class="math inline">\(\bar{x}\)</span> la media muestral, y <span class="math inline">\(\mu\)</span> la media poblacional. En el caso de la varianza muestral se usa en el denominador <span class="math inline">\(N-1\)</span>, lo que se conoce como grados de libertad (<span class="math inline">\(df \ o \ \nu\)</span>). Porqué <span class="math inline">\(N-1\)</span>, porque para poder calcular la varianza se necesita saber la media, y si se conoce la media no importa la cantidad de datos que tenga el último dato va a estar condicionado para satisfacer el valor de la media, o sea todos los datos menos uno pueden variar libremente.</p>
<p>Un ejemplo de puede mostrar con los datos 8, 10, 5, 12, 10, 15. En este caso <span class="math inline">\(N=6,\ \bar{x}=60/6=10,\ \sum_{i=1}^{N}{\left(x_i - \bar{x}\right)^2}=58,\ s^2=\frac{58}{6-1}=11.6 \ unidades^2\)</span>. En <strong>R</strong> se usa la función <code>var</code> para obtener la varianza de un vector.</p>
<pre class="sourceCode r"><code class="sourceCode r">vec =<span class="st"> </span><span class="kw">c</span>(<span class="dv">8</span>, <span class="dv">10</span>,  <span class="dv">5</span>, <span class="dv">12</span>, <span class="dv">10</span>, <span class="dv">15</span>)
<span class="kw">var</span>(vec)</code></pre>
<pre><code>## [1] 11.6</code></pre>
</div>
<div id="desviación-estándar-s" class="section level4">
<h4><span class="header-section-number">9.4.2.3</span> Desviación estándar (<span class="math inline">\(s\)</span>)</h4>
<p>Esta medida es la más utilizada, ya que se encuentra en las mismas unidades (escala) de los datos originales, dado que es simplemente la raíz cuadrada de la varianza (Ecuación <a href="estadística-descriptiva-univariable.html#eq:sd">(9.8)</a>), lo que la hace más fácil de interpretar y comprender.</p>
<p><span class="math display" id="eq:sd">\[\begin{equation}
  s = \sqrt{s^2} = \sqrt{\frac{\sum_{i=1}^{N}{\left(x_i - \bar{x}\right)^2}}{N-1}}\\
  \sigma = \sqrt{\sigma^2} = \sqrt{\frac{\sum_{i=1}^{N}{\left(x_i - \mu\right)}}{N}}
  \tag{9.8}
\end{equation}\]</span></p>
<p>Siguiendo con los datos del ejemplo de la varianza se tiene que <span class="math inline">\(s = \sqrt{s^2} = \sqrt{11.6} = 3.4 \ unidades\)</span>. En <strong>R</strong> se tiene la función <code>sd</code> para calcular esta medida directamente.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sd</span>(vec)</code></pre>
<pre><code>## [1] 3.405877</code></pre>
<p>Visualmente (Figura <a href="estadística-descriptiva-univariable.html#fig:sd">9.8</a>) se puede mostrar como al incrementar la desviación estándar la curva de densidad de los datos se aplana más.</p>
<div class="figure" style="text-align: center"><span id="fig:sd"></span>
<img src="geolonum_files/figure-html/sd-1.png" alt="Curvas de densidad con diferentes desviaciones estándar, donde a mayor desviación estándar más aplanada la curva y a menor desviación estándar más empinada la curva" width="70%" />
<p class="caption">
Figura 9.8: Curvas de densidad con diferentes desviaciones estándar, donde a mayor desviación estándar más aplanada la curva y a menor desviación estándar más empinada la curva
</p>
</div>
<p>Como se va a ver más adelante hay una relación entre la desviación estándar y la media que se ve reflejada en la distribución normal (Figura <a href="estadística-descriptiva-univariable.html#fig:sd-norm">9.9</a>). Típicamente se asocia que el 68% de los datos se encuentran a <span class="math inline">\(1\ s\)</span> de la media, el 95% de los datos se encuentran a <span class="math inline">\(2\ s\)</span> de la media, y el 99% de los datos se encuentran a <span class="math inline">\(3\ s\)</span> de la media.</p>
<div class="figure" style="text-align: center"><span id="fig:sd-norm"></span>
<img src="images/sd-norm.png" alt="Relación entre desviación estándar y media en la distribución normal. Tomado de: http://algebra2.thinkport.org/module3/images/xyz-page2-graph.jpg" width="70%" />
<p class="caption">
Figura 9.9: Relación entre desviación estándar y media en la distribución normal. Tomado de: <a href="http://algebra2.thinkport.org/module3/images/xyz-page2-graph.jpg" class="uri">http://algebra2.thinkport.org/module3/images/xyz-page2-graph.jpg</a>
</p>
</div>
</div>
<div id="rango-intercuartil-iqr" class="section level4">
<h4><span class="header-section-number">9.4.2.4</span> Rango intercuartil (<span class="math inline">\(IQR\)</span>)</h4>
<p>Mide la dispersión central de los datos, ya que se toma únicamente el 50% central de los datos, al ser la diferencia entre el tercer cuartil (<span class="math inline">\(Q_3\)</span>) y primer cuartil (<span class="math inline">\(Q_1\)</span>), ver Ecuación <a href="estadística-descriptiva-univariable.html#eq:iqr">(9.9)</a>. Se considera más robusta que la desviación estándar al no tomar en cuenta valores extremos. De hecho, valores extremos o atípicos suelen identificarse cuando se desvían más de 3 veces el <span class="math inline">\(IQR\)</span> con respecto a la mediana.</p>
<p><span class="math display" id="eq:iqr">\[\begin{equation}
  IQR = Q_3 - Q_1
  \tag{9.9}
\end{equation}\]</span></p>
<p>En <strong>R</strong> se tiene el comando <code>IQR</code> para calcular esta medida, como se muestra a continuación.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">10</span>)
vec =<span class="st"> </span><span class="kw">rchisq</span>(<span class="dv">60</span>,<span class="dv">3</span>)
<span class="kw">IQR</span>(vec)</code></pre>
<pre><code>## [1] 2.533682</code></pre>
</div>
<div id="mediana-de-la-desviación-absoluta-mad" class="section level4">
<h4><span class="header-section-number">9.4.2.5</span> Mediana de la desviación absoluta (<span class="math inline">\(mad\)</span>)</h4>
<p>Se calcula usando la Ecuación <a href="estadística-descriptiva-univariable.html#eq:mad">(9.10)</a> y en general se considera más robusta que la desviación estándar y el rango intercuartil cuando se presentan datos extremos o atípicos y cuando la distribución es asimétrica. Se le aplica un factor de conversión de 1.4826 para cumplir con supuestos de normalidad.</p>
<p><span class="math display" id="eq:mad">\[\begin{equation}
  mad = Me\left(\left|x_i - Me(x)\right|\right) * 1.4826
  \tag{9.10}
\end{equation}\]</span></p>
<p>Usando los datos generados para <span class="math inline">\(IQR\)</span> se puede calcular esta medida usando <code>mad</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mad</span>(vec)</code></pre>
<pre><code>## [1] 1.769578</code></pre>
</div>
<div id="coeficiente-de-variación-cv" class="section level4">
<h4><span class="header-section-number">9.4.2.6</span> Coeficiente de variación (<span class="math inline">\(cv\)</span>)</h4>
<p>Esta es una medida estandarizada (Ecuación <a href="estadística-descriptiva-univariable.html#eq:cv">(9.11)</a>), lo que nos va a permitir comparar la dispersión entre dos poblaciones distintas e incluso, comparar la variación producto de dos variables diferentes (que pueden provenir de una misma población). Si comparamos la dispersión en varios conjuntos de observaciones tendrá menor dispersión aquella que tenga menor coeficiente de variación.</p>
<p><span class="math display" id="eq:cv">\[\begin{equation}
  cv = \frac{s}{\bar{x}}*100
  \tag{9.11}
\end{equation}\]</span></p>
<p>Un ejemplo se muestra a continuación. Para un grupo de datos <span class="math inline">\(\bar{x}=20, s = 4\)</span>, entonces <span class="math inline">\(cv = 4/20 = 0.2 = 20\%\)</span>. Para un segundo grupo <span class="math inline">\(\bar{x} = 48, s = 6\)</span>, entonces <span class="math inline">\(cv = 6/48 = 0.125 = 12.5\%\)</span>. Se concluye que el primer grupo tiene mayor variabilidad relativa con respecto a su media, lo que no se podría concluir de solo fijarse en la desviación estándar.</p>
<p>En <strong>R</strong> el paquete <em>DescTools</em> <span class="citation">(Signorell, <a href="#ref-R-DescTools">2020</a>)</span> tiene la función <code>CoefVar</code>, y si la aplicamos a los datos generados para <span class="math inline">\(IQR\)</span> tenemos:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">CoefVar</span>(vec)</code></pre>
<pre><code>## [1] 0.7334606</code></pre>
</div>
</div>
<div id="medidas-de-posición" class="section level3">
<h3><span class="header-section-number">9.4.3</span> Medidas de posición</h3>
<p>Estas medidas corresponden con números que distribuyen los datos ordenados de la muestra en grupos de aproximadamente del mismo tamaño, con el propósito de resaltar su ubicación relativa. Estos números se denominan <strong>cuantiles</strong> en forma genérica.</p>
<div id="cuartiles" class="section level4">
<h4><span class="header-section-number">9.4.3.1</span> Cuartiles</h4>
<p>Los cuartiles son los tres valores de la variable que dividen a un conjunto de datos ordenados en cuatro partes iguales (Figura <a href="estadística-descriptiva-univariable.html#fig:cuartiles">9.10</a>).</p>
<ul>
<li>Primer Cuartil (<span class="math inline">\(Q1\)</span>): A la izquierda de <span class="math inline">\(Q1\)</span> están incluidos 25% de los datos (aproximadamente), y a la derecha de <span class="math inline">\(Q1\)</span> están el 75% de los datos (aproximadamente).</li>
<li>Segundo Cuartil (<span class="math inline">\(Q2\)</span>): Igual que la mediana divide al grupo de datos en dos partes, cada una con el 50% de los datos (aproximadamente).</li>
<li>Tercer Cuartil (<span class="math inline">\(Q3\)</span>): A la izquierda de <span class="math inline">\(Q3\)</span> están incluidos 75% de los datos (aproximadamente), y a la derecha de <span class="math inline">\(Q3\)</span> están el 25% de los datos (aproximadamente).</li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:cuartiles"></span>
<img src="images/cuartiles.png" alt="Representación de los cuartiles. Tomado de: http://dieumsnh.qfb.umich.mx/estadistica/medidasd%20de%20posicion.htm" width="70%" />
<p class="caption">
Figura 9.10: Representación de los cuartiles. Tomado de: <a href="http://dieumsnh.qfb.umich.mx/estadistica/medidasd%20de%20posicion.htm" class="uri">http://dieumsnh.qfb.umich.mx/estadistica/medidasd%20de%20posicion.htm</a>
</p>
</div>
</div>
<div id="deciles" class="section level4">
<h4><span class="header-section-number">9.4.3.2</span> Deciles</h4>
<p>Los deciles son los nueve valores de la variable que dividen a un conjunto de datos ordenados en diez partes iguales (Figura <a href="estadística-descriptiva-univariable.html#fig:deciles">9.11</a>).</p>
<ul>
<li>Primer Decil (D1): A la izquierda de D1 están incluidos 10% de los datos (aproximadamente), y a la derecha de D1 están el 90% de los datos (aproximadamente).</li>
<li>Segundo Decil (D2): A la izquierda de D1 están incluidos 20% de los datos (aproximadamente), y a la derecha de D1 están el 80% de los datos (aproximadamente)</li>
<li>D5 coincide con la mediana.</li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:deciles"></span>
<img src="images/deciles.png" alt="Representación de los deciles. Tomado de: http://dieumsnh.qfb.umich.mx/estadistica/medidasd%20de%20posicion.htm" width="70%" />
<p class="caption">
Figura 9.11: Representación de los deciles. Tomado de: <a href="http://dieumsnh.qfb.umich.mx/estadistica/medidasd%20de%20posicion.htm" class="uri">http://dieumsnh.qfb.umich.mx/estadistica/medidasd%20de%20posicion.htm</a>
</p>
</div>
<p>En <strong>R</strong> los cuantiles se pueden obtener con la función <code>quantile</code> y definiendo el argumento <code>probs</code>, donde corresponde con un vector de valores entre 0 y 1, para los cuantiles deseados.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">quantile</span>(vec, <span class="dt">probs =</span> <span class="kw">c</span>(.<span class="dv">25</span>,.<span class="dv">5</span>,.<span class="dv">75</span>)) <span class="co"># para cuartiles</span></code></pre>
<pre><code>##      25%      50%      75% 
## 1.212222 2.156949 3.745904</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">quantile</span>(vec, <span class="dt">probs =</span> <span class="kw">seq</span>(.<span class="dv">1</span>,.<span class="dv">9</span>,.<span class="dv">1</span>)) <span class="co"># para deciles</span></code></pre>
<pre><code>##       10%       20%       30%       40%       50%       60%       70%       80% 
## 0.6815646 0.8654207 1.3201193 1.8411737 2.1569488 2.4933732 3.1549380 4.0521953 
##       90% 
## 5.4816144</code></pre>
</div>
</div>
<div id="medidas-de-forma" class="section level3">
<h3><span class="header-section-number">9.4.4</span> Medidas de forma</h3>
<p>Estas medidas se usan para describir numéricamente la forma aproximada de la distribución de los datos.</p>
<div id="asimetría-skewness" class="section level4">
<h4><span class="header-section-number">9.4.4.1</span> Asimetría (skewness)</h4>
<p>Se dice que una distribución es asimétrica cuando la media, mediana y moda no coinciden y la distribución muestra una forma diferente a la “campana”, con una cola más alargada que la otra.</p>
<p>Se pueden identificar dos tipos de asimetría: positiva (hacia la derecha) o negativa (hacia la izquierda), ver Figuras <a href="estadística-descriptiva-univariable.html#fig:asim1">9.12</a> y <a href="estadística-descriptiva-univariable.html#fig:asim2">9.13</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:asim1"></span>
<img src="images/asimetria1.png" alt="Asimetría con el nombre de la dirección: hacia la izquierda o derecha. Tomado de: http://2.bp.blogspot.com/_bXZg80tWNts/S4SBFgzljbI/AAAAAAAAAd0/72BnnqmoA7g/s320/asimetria.gif" width="70%" />
<p class="caption">
Figura 9.12: Asimetría con el nombre de la dirección: hacia la izquierda o derecha. Tomado de: <a href="http://2.bp.blogspot.com/_bXZg80tWNts/S4SBFgzljbI/AAAAAAAAAd0/72BnnqmoA7g/s320/asimetria.gif" class="uri">http://2.bp.blogspot.com/_bXZg80tWNts/S4SBFgzljbI/AAAAAAAAAd0/72BnnqmoA7g/s320/asimetria.gif</a>
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:asim2"></span>
<img src="images/asimetria2.png" alt="Asimetría con el nombre del signo: positiva o negativa. Tomado de: http://pro.arcgis.com/en/pro-app/tool-reference/spatial-statistics/" width="70%" />
<p class="caption">
Figura 9.13: Asimetría con el nombre del signo: positiva o negativa. Tomado de: <a href="http://pro.arcgis.com/en/pro-app/tool-reference/spatial-statistics/" class="uri">http://pro.arcgis.com/en/pro-app/tool-reference/spatial-statistics/</a>
</p>
</div>
<p>Si la asimetría es positiva se denomina a la derecha (media a la derecha de la mediana y moda) y si es negativa se denomina a la izquierda (media a la izquierda de la mediana y moda). Se pueden considerar como asimetrías importantes y que pueden afectar los datos aquellas que anden cerca de 1 y definittivamente las superiores a 1.</p>
<p>Se puede eliminar o reducir significativamente la asimetría usando transformaciones sobre los datos (Figura <a href="estadística-descriptiva-univariable.html#fig:asim3">9.14</a>). La transformación logarítmica se puede usar cuando la distribución es asimétrica a la derecha (positiva), y la transformación exponencial se puede usar cuando la distribución es asimétrica a la izquierda (negativa).</p>
<div class="figure" style="text-align: center"><span id="fig:asim3"></span>
<img src="images/asimetria3-trans.png" alt="Transformaciones que se pueden aplicar sobre los datos para reducir la asimetría. Tomado de: http://pro.arcgis.com/en/pro-app/tool-reference/spatial-statistics/" width="70%" />
<p class="caption">
Figura 9.14: Transformaciones que se pueden aplicar sobre los datos para reducir la asimetría. Tomado de: <a href="http://pro.arcgis.com/en/pro-app/tool-reference/spatial-statistics/" class="uri">http://pro.arcgis.com/en/pro-app/tool-reference/spatial-statistics/</a>
</p>
</div>
</div>
<div id="curtosis-kurtosis" class="section level4">
<h4><span class="header-section-number">9.4.4.2</span> Curtosis (kurtosis)</h4>
<p>Caracteriza el apuntalamiento (puntiagudez) de la distribución, si la distribución tiene un pico distintivo o es relativamente plana, y la concentración de valores alrededor de la media. Los nombres que puede tomar se presentan en la Figura <a href="estadística-descriptiva-univariable.html#fig:curt1">9.15</a> y ejemplos de datos con diferentes curtosis se presentan en la Figura <a href="estadística-descriptiva-univariable.html#fig:curt2">9.16</a>.</p>

<div class="figure" style="text-align: center"><span id="fig:curt1"></span>
<img src="images/curtosis1.png" alt="Nombres de la curtosis que se le asigna a la distribución de los datos según el valor estimado de la curtosis. Leptocúrtica cuando \(k&gt;0\), mesocúrtica cuando \(k \approx 0\), y platicúrtica cuando \(k&lt;0\). Tomado de: http://www.spssfree.com/curso-de-spss/curso/5-19.gif." width="70%" />
<p class="caption">
Figura 9.15: Nombres de la curtosis que se le asigna a la distribución de los datos según el valor estimado de la curtosis. Leptocúrtica cuando <span class="math inline">\(k&gt;0\)</span>, mesocúrtica cuando <span class="math inline">\(k \approx 0\)</span>, y platicúrtica cuando <span class="math inline">\(k&lt;0\)</span>. Tomado de: <a href="http://www.spssfree.com/curso-de-spss/curso/5-19.gif" class="uri">http://www.spssfree.com/curso-de-spss/curso/5-19.gif</a>.
</p>
</div>

<div class="figure" style="text-align: center"><span id="fig:curt2"></span>
<img src="images/curtosis2.png" alt="Ejemplo de alta curtosis (izquierda) y baja curtosis (derecha) (Trauth, 2015)." width="70%" />
<p class="caption">
Figura 9.16: Ejemplo de alta curtosis (izquierda) y baja curtosis (derecha) <span class="citation">(Trauth, <a href="#ref-trauth2015">2015</a>)</span>.
</p>
</div>
<p>En <strong>R</strong> násico no hay una función para calcular la asimetría ni la curtosis, pero el paquete <em>DescTools</em> tiene la función <code>Skew</code> para asimetría y <code>Kurt</code> para curtosis. Usando los datos anteriores tenemos:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">Skew</span>(vec)</code></pre>
<pre><code>## [1] 1.06636</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">Kurt</span>(vec)</code></pre>
<pre><code>## [1] 0.5057107</code></pre>
<p>Con los resultados anteriores se tiene una asimetría positiva (hacia la derecha) bastante importante, y una curtosis positiva indicando que los datos presentan un apuntalamiento importante en vez de que sean más dispersos.</p>
</div>
</div>
</div>
<div id="resumen-general" class="section level2">
<h2><span class="header-section-number">9.5</span> Resumen general</h2>
<p>En <strong>R</strong> hay varias funciones que presentan resúmenes generales presentando varias medidas (revisar <a href="basico.html#descripciones-generales-globales">Descripciones generales (globales)</a>), aquí se presenta la función <code>descr</code> del paquete <em>summarytools</em> <span class="citation">(Comtois, <a href="#ref-R-summarytools">2019</a>)</span>, que se usa para datos cuantitativos, si se tuvieran datos cualitativos se puede utilizar <code>freq</code> o la tabla de frecuencias como se presentó anteriormente (<a href="estadística-descriptiva-univariable.html#tablas-de-frecuencias">Tablas de frecuencias</a>).</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">descr</span>(vec)</code></pre>
<pre><code>## Descriptive Statistics  
## vec  
## N: 60  
## 
##                        vec
## ----------------- --------
##              Mean     2.62
##           Std.Dev     1.92
##               Min     0.31
##                Q1     1.19
##            Median     2.16
##                Q3     3.75
##               Max     8.56
##               MAD     1.77
##               IQR     2.53
##                CV     0.73
##          Skewness     1.07
##       SE.Skewness     0.31
##          Kurtosis     0.51
##           N.Valid    60.00
##         Pct.Valid   100.00</code></pre>
<p>Usando esta función (<code>descr</code>) podemos comparar las diferentes medidas entre un vector de datos sin valores extremos y otro con 1 valor extremo, para ver cómo afecta o no este dato las diferentes medidas.</p>
<pre class="sourceCode r"><code class="sourceCode r">original =<span class="st"> </span><span class="kw">c</span>(<span class="dv">22</span>,<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">16</span>,<span class="dv">15</span>,<span class="dv">15</span>,<span class="dv">24</span>,<span class="dv">19</span>,<span class="dv">15</span>,<span class="dv">19</span>,<span class="dv">18</span>,<span class="dv">16</span>,<span class="dv">18</span>,<span class="dv">12</span>,<span class="dv">17</span>,<span class="dv">17</span>,<span class="dv">11</span>,<span class="dv">18</span>)
outlier =<span class="st"> </span><span class="kw">c</span>(<span class="dv">22</span>,<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">16</span>,<span class="dv">15</span>,<span class="dv">15</span>,<span class="dv">24</span>,<span class="dv">19</span>,<span class="dv">15</span>,<span class="dv">19</span>,<span class="dv">18</span>,<span class="dv">16</span>,<span class="dv">18</span>,<span class="dv">12</span>,<span class="dv">17</span>,<span class="dv">17</span>,<span class="dv">11</span>,<span class="dv">180</span>)
DF =<span class="st"> </span><span class="kw">tibble</span>(original, outlier)
<span class="kw">descr</span>(DF)</code></pre>
<pre><code>## Descriptive Statistics  
## DF  
## N: 18  
## 
##                     original   outlier
## ----------------- ---------- ---------
##              Mean      16.22     25.22
##           Std.Dev       3.81     38.81
##               Min      10.00     10.00
##                Q1      15.00     15.00
##            Median      16.50     16.50
##                Q3      18.00     19.00
##               Max      24.00    180.00
##               MAD       2.22      2.97
##               IQR       3.00      3.75
##                CV       0.24      1.54
##          Skewness       0.02      3.50
##       SE.Skewness       0.54      0.54
##          Kurtosis      -0.64     11.06
##           N.Valid      18.00     18.00
##         Pct.Valid     100.00    100.00</code></pre>
<p>Viendo el resumen con las diferentes medidas y comparándolas, se puede observar como las medidas de media, desviación estándar, coeficiente de variación, asimetría y curtosis se ven muy afectadas por un único valor extremo, mientras que los cuantiles (incluyendo la mediana) y el <em>mad</em> no se ven afectadas del todo o muy poco.</p>

</div>
</div>
<h3>Referencias</h3>
<div id="refs" class="references">
<div id="ref-R-summarytools">
<p>Comtois, D. (2019). <em>summarytools: Tools to Quickly and Neatly Summarize Data</em>. <a href="https://CRAN.R-project.org/package=summarytools">https://CRAN.R-project.org/package=summarytools</a></p>
</div>
<div id="ref-R-DescTools">
<p>Signorell, A. (2020). <em>DescTools: Tools for Descriptive Statistics</em>. <a href="https://CRAN.R-project.org/package=DescTools">https://CRAN.R-project.org/package=DescTools</a></p>
</div>
<div id="ref-trauth2015">
<p>Trauth, M. (2015). <em>MATLAB® Recipes for Earth Sciences</em> (4.ª ed.). Springer-Verlag Berlin Heidelberg.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introducción-a-estadística.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="estadística-descriptiva-bivariable.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
